// Ek soru bankası A — 9.2, 9.3, 10.1, 10.2, 10.3 temaları (her temada en az 15 soru hedefi)
// seed-questions.ts tarafından import edilir.
import type { SoruKayit } from "./questions-bank-extra";

export const EK_SORULAR910: SoruKayit[] = [
  // ===== 9.2 Çeşitlilik (ek) =====
  {
    kod: "KİM.9.2.6",
    zorluk: 3,
    soru: "Na₂O bileşiğinin adı aşağıdakilerden hangisidir?",
    aciklama: "Na⁺ sodyum, O²⁻ oksit iyonudur; metal + ametal iyonik bileşiklerde metal adı + ametal adı (-ür) kullanılır: sodyum oksit.",
    secenekler: ["Sodyum oksit", "Sodyum peroksit", "Disodyum oksijen", "Sodyum dioksit"],
    dogru: 0,
  },
  {
    kod: "KİM.9.2.13",
    zorluk: 2,
    soru: "Sıvıların yüzey gerilimi aşağıdaki hangi durumda azalır?",
    aciklama: "Sıcaklık arttıkça moleküller arası çekim zayıflar, yüzey gerilimi azalır. Deterjan/sabun da yüzey gerilimini düşürür.",
    secenekler: [
      "Sıcaklık arttığında",
      "Sıcaklık azaldığında",
      "Moleküller arası çekim kuvveti arttığında",
      "Sıvının saflığı arttığında",
    ],
    dogru: 0,
  },

  // ===== 9.3 Sürdürülebilirlik (ek) =====
  {
    kod: "KİM.9.3.1",
    zorluk: 1,
    soru: "Nanoparçacıkların boyutu yaklaşık hangi aralıktadır?",
    aciklama: "Nanoparçacıklar 1-100 nanometre (nm) boyut aralığındaki taneciklerdir; 1 nm, metrenin milyarda biridir.",
    secenekler: ["1-100 nm", "1-100 mikrometre", "1-100 milimetre", "1-100 santimetre"],
    dogru: 0,
  },
  {
    kod: "KİM.9.3.1",
    zorluk: 2,
    soru: "Bir metalin nanoparçacık hâline getirilmesiyle aşağıdaki özelliklerinden hangisi değişir?",
    aciklama: "Boyut küçüldükçe yüzey alanı/hacim oranı artar; bu nedenle erime sıcaklığı, renk ve katalitik etkinlik gibi özellikler değişir (örn. altın nanoparçacıkları kırmızı görünür).",
    secenekler: [
      "Yüzey alanı/hacim oranı ve buna bağlı özellikler",
      "Sadece kütlesi",
      "Atomlarının yapısı",
      "Kimyasal sembolü",
    ],
    dogru: 0,
  },
  {
    kod: "KİM.9.3.1",
    zorluk: 3,
    soru: "Evsel atıklardan metal nanoparçacık elde edilirken izlenen temel yaklaşım nedir?",
    aciklama: "Atık kaynaklardan (ör. eski elektronik, pil) metal iyonları çözeltiye alınır; uygun bir indirgeyici (ör. bitki özü) ile metal iyonları nanoparçacık hâline indirgenir. Böylece atık değere dönüştürülür.",
    secenekler: [
      "Atıktaki metal iyonlarını çözeltiye alıp indirgeyerek nanoparçacık üretmek",
      "Atığı doğrudan çöpe atmak",
      "Atığı yüksek sıcaklıkta yakmak",
      "Atığı suda bekletmek",
    ],
    dogru: 0,
  },
  {
    kod: "KİM.9.3.1",
    zorluk: 2,
    soru: "Nanoparçacık üretiminde 'yeşil sentez' denildiğinde genellikle hangisi kastedilir?",
    aciklama: "Yeşil sentezde toksik kimyasallar yerine bitki özü, mikroorganizma gibi çevre dostu indirgeyiciler kullanılır.",
    secenekler: [
      "Bitki özü gibi çevre dostu maddelerle sentez",
      "Yüksek sıcaklıkta fırında sentez",
      "Radyoaktif maddeyle sentez",
      "Plastik atıkla sentez",
    ],
    dogru: 0,
  },
  {
    kod: "KİM.9.3.1",
    zorluk: 2,
    soru: "Deneyde gümüş nanoparçacığı oluştuğu nasıl anlaşılır?",
    aciklama: "Gümüş nanoparçacıkları ışıkla etkileşerek sarı-kahverengi renk verir (yüzey plazmon rezonansı); renk değişimi oluşumun göstergesidir.",
    secenekler: [
      "Çözelti sarı-kahverengi renk alır",
      "Çözelti kaynar",
      "Gaz kabarcıkları çıkar",
      "Katı dibe çöker ve renk değişmez",
    ],
    dogru: 0,
  },
  {
    kod: "KİM.9.3.1",
    zorluk: 3,
    soru: "Aynı metalin nanoparçacığı ile kütlesi eşit büyük parçası karşılaştırıldığında hangisi doğrudur?",
    aciklama: "Nanoparçacıkta yüzeydeki atom oranı çok daha fazladır; bu yüzden kimyasal etkinliği (örn. katalizörlük) genellikle daha yüksektir.",
    secenekler: [
      "Nanoparçacığın yüzey atomu oranı ve etkinliği daha yüksektir",
      "İkisi de aynı etkinliğe sahiptir",
      "Büyük parça her zaman daha etkindir",
      "Nanoparçacık kimyasal tepkimeye girmez",
    ],
    dogru: 0,
  },
  {
    kod: "KİM.9.3.2",
    zorluk: 2,
    soru: "Metal nanoparçacıkların ekosisteme karışması hangi yolla en çok gerçekleşir?",
    aciklama: "Nanoparçacık içeren ürünlerin (kozmetik, tekstil, boya) kullanımı ve yıkanmasıyla atık sulara karışır; arıtma sistemlerinde tam tutulamazsa su ve toprağa ulaşır.",
    secenekler: [
      "Ürünlerin kullanımı ve atık sularla",
      "Sadece volkanik patlamalarla",
      "Yalnızca uzay tozlarıyla",
      "Sadece fotosentezle",
    ],
    dogru: 0,
  },
  {
    kod: "KİM.9.3.2",
    zorluk: 2,
    soru: "Sucul ekosistemde aşırı metal (ör. gümüş, bakır) iyonu birikimi hangi sonuca yol açabilir?",
    aciklama: "Yüksek metal derişimi su canlıları için toksiktir; besin zincirinde birikebilir ve ekosistem dengesini bozar.",
    secenekler: [
      "Su canlıları için toksik etki ve besin zincirinde birikim",
      "Oksijen miktarının artması",
      "Canlı çeşitliliğinin artması",
      "Hiçbir etki olmaz",
    ],
    dogru: 0,
  },
  {
    kod: "KİM.9.3.2",
    zorluk: 1,
    soru: "Aşağıdakilerden hangisi alaşımların kullanımına bir örnek değildir?",
    aciklama: "Çelik (demir+karbon), pirinç (bakır+çinko) ve tunç (bakır+kalay) alaşımdır. Saf demir, alaşım değildir.",
    secenekler: ["Saf demir", "Çelik", "Pirinç", "Tunç"],
    dogru: 0,
  },
  {
    kod: "KİM.9.3.2",
    zorluk: 2,
    soru: "Atık pillerin doğaya atılmasının temel zararı nedir?",
    aciklama: "Piller ağır metal (cıva, kadmiyum, kurşun vb.) içerir; toprağa ve suya karışarak ekosistemi kirletir. Bu yüzden atık pil toplama kutularına atılmalıdır.",
    secenekler: [
      "Ağır metallerle toprak ve suyu kirletmesi",
      "Plastik üretimini artırması",
      "Hava sıcaklığını artırması",
      "Doğada hızla parçalanıp gübre olması",
    ],
    dogru: 0,
  },
  {
    kod: "KİM.9.3.2",
    zorluk: 2,
    soru: "Metal nanoparçacıkların antibakteriyel özelliğinden yararlanılan ürün hangisidir?",
    aciklama: "Gümüş nanoparçacıkları antibakteriyel özellikleri nedeniyle yara bantları, tekstil ve gıda ambalajlarında kullanılır.",
    secenekler: [
      "Antibakteriyel yara bantları",
      "İçme suyu arıtma kimyasalı olarak",
      "Benzin katkısı olarak",
      "Gübre olarak",
    ],
    dogru: 0,
  },
  {
    kod: "KİM.9.3.2",
    zorluk: 3,
    soru: "Nanoparçacık içeren bir ürün seçerken çevre bilincine sahip bir tüketici öncelikle neye dikkat etmelidir?",
    aciklama: "Ürünün çevreye salımı, etiketindeki içerik ve yetkili kurum onayı değerlendirilmelidir; gereksiz nanomalzeme içeren ürünlerden kaçınılması ekosistemi korur.",
    secenekler: [
      "İçeriği ve çevresel etkilerini sorgulamaya",
      "Sadece ambalaj rengine",
      "Sadece fiyatına",
      "Markasının popülerliğine",
    ],
    dogru: 0,
  },
  {
    kod: "KİM.9.3.2",
    zorluk: 3,
    soru: "Metallerin ekosistemde canlılarda birikerek besin zincirinde derişmesine ne ad verilir?",
    aciklama: "Biyobirikim: canlı vücudunda madde birikimi; biyolojik büyüme ile besin zincirinin üst basamaklarında derişimin artmasına biyolojik çoğalma denir.",
    secenekler: ["Biyobirikim", "Fotosentez", "Ayrışma", "Buharlaşma"],
    dogru: 0,
  },

  // ===== 10.1 Etkileşim (ek) =====
  {
    kod: "KİM.10.1.1",
    zorluk: 1,
    soru: "Aşağıdakilerden hangisi kimyasal değişimin gözlenebilir bir kanıtı değildir?",
    aciklama: "Hâl değişimi (ör. buzun erimesi) fiziksel değişimdir. Renk değişimi, gaz çıkışı, çökelek oluşumu ve enerji değişimi kimyasal değişim kanıtlarıdır.",
    secenekler: ["Buzun erimesi", "Renk değişimi", "Gaz çıkışı", "Çökelek oluşumu"],
    dogru: 0,
  },
  {
    kod: "KİM.10.1.1",
    zorluk: 2,
    soru: "Demir telin nemli ortamda paslanması hangi tür değişimdir?",
    aciklama: "Paslanmada demir, oksijenle tepkimeye girerek yeni bir madde (demir oksit) oluşturur; bu kimyasal değişimdir.",
    secenekler: ["Kimyasal değişim", "Fiziksel değişim", "Hâl değişimi", "Çözünme"],
    dogru: 0,
  },
  {
    kod: "KİM.10.1.3",
    zorluk: 2,
    soru: "CH₄ + 2O₂ → CO₂ + 2H₂O tepkimesi hangi tepkime türüne örnektir?",
    aciklama: "Bir maddenin oksijenle ısı ve ışık vererek tepkimesi yanma tepkimesidir; organik yakıtların yanması genelde CO₂ ve H₂O üretir.",
    secenekler: ["Yanma tepkimesi", "Analiz tepkimesi", "Çökelme tepkimesi", "Nötralleşme tepkimesi"],
    dogru: 0,
  },
  {
    kod: "KİM.10.1.3",
    zorluk: 2,
    soru: "CaCO₃ → CaO + CO₂ tepkimesi hangi tepkime türüdür?",
    aciklama: "Tek bir bileşiğin daha basit maddelere ayrışması analiz (ayrışma) tepkimesidir.",
    secenekler: ["Analiz (ayrışma)", "Sentez", "Yanma", "Yer değiştirme"],
    dogru: 0,
  },
  {
    kod: "KİM.10.1.4",
    zorluk: 2,
    soru: "1 mol madde kaç tanecik içerir?",
    aciklama: "1 mol, 6,02×10²³ (Avogadro sayısı) tanecik içerir.",
    secenekler: ["6,02×10²³", "3,01×10²³", "1,0×10²³", "6,02×10²²"],
    dogru: 0,
  },
  {
    kod: "KİM.10.1.6",
    zorluk: 2,
    soru: "Al + HCl → AlCl₃ + H₂ tepkimesinin denkleştirilmiş hâli aşağıdakilerden hangisidir?",
    aciklama: "2Al + 6HCl → 2AlCl₃ + 3H₂: Al sayısı 2, Cl sayısı 6, H sayısı 6 olur.",
    secenekler: [
      "2Al + 6HCl → 2AlCl₃ + 3H₂",
      "Al + HCl → AlCl₃ + H₂",
      "2Al + 3HCl → 2AlCl₃ + 3H₂",
      "Al + 3HCl → AlCl₃ + H₂",
    ],
    dogru: 0,
  },
  {
    kod: "KİM.10.1.9",
    zorluk: 3,
    soru: "Sabit sıcaklıkta bir gazın hacmi azaltılırsa basıncı nasıl değişir?",
    aciklama: "Boyle-Mariotte yasasına göre sabit sıcaklıkta basınç-hacim çarpımı sabittir; hacim azalınca basınç artar.",
    secenekler: ["Artar", "Azalır", "Değişmez", "Önce artar sonra azalır"],
    dogru: 0,
  },
  {
    kod: "KİM.10.1.10",
    zorluk: 3,
    soru: "İdeal gaz denklemi aşağıdakilerden hangisidir?",
    aciklama: "İdeal gaz denklemi PV = nRT'tir; P basınç, V hacim, n mol sayısı, R gaz sabiti, T mutlak sıcaklıktır.",
    secenekler: ["PV = nRT", "PV = nT", "P = nRT", "PV = RT/n"],
    dogru: 0,
  },

  // ===== 10.2 Çeşitlilik (ek) =====
  {
    kod: "KİM.10.2.1",
    zorluk: 1,
    soru: "Şekerin suda çözünmesi sırasında oluşan karışım hangisidir?",
    aciklama: "Şeker suda moleküler düzeyde dağılır ve homojen karışım (çözelti) oluşur.",
    secenekler: ["Homojen karışım (çözelti)", "Süspansiyon", "Emülsiyon", "Kolloid"],
    dogru: 0,
  },
  {
    kod: "KİM.10.2.2",
    zorluk: 2,
    soru: "Yağın suda çözünmemesinin temel nedeni nedir?",
    aciklama: "Su polar, yağ ise apolardır. 'Benzer benzeri çözer' ilkesine göre polar çözücü apolar maddeleri iyi çözmez.",
    secenekler: [
      "Yağ apolar, su polar olduğu için",
      "Yağın yoğunluğu düşük olduğu için",
      "Suyun kaynama noktası yüksek olduğu için",
      "Yağın molekül kütlesi büyük olduğu için",
    ],
    dogru: 0,
  },
  {
    kod: "KİM.10.2.3",
    zorluk: 2,
    soru: "Tuzun suda çözünmesi sırasında gerçekleşen olay aşağıdakilerden hangisidir?",
    aciklama: "İyonik katı (NaCl) suda Na⁺ ve Cl⁻ iyonlarına ayrışarak çözünür; bu iyonik çözünmedir.",
    secenekler: [
      "İyonlarına ayrışarak çözünme",
      "Kovalent bağlarının koparak atomlaşma",
      "Kimyasal olarak yeni bileşik oluşturma",
      "Suda asılı kalarak süspansiyon oluşturma",
    ],
    dogru: 0,
  },
  {
    kod: "KİM.10.2.4",
    zorluk: 1,
    soru: "Bir maddenin 100 g suda belirli sıcaklıkta çözünebilen en fazla kütlesine ne denir?",
    aciklama: "Çözünürlük; genellikle g/100 g su cinsinden ifade edilir ve sıcaklığa bağlıdır.",
    secenekler: ["Çözünürlük", "Derişim", "Molalite", "Seyreltme"],
    dogru: 0,
  },
  {
    kod: "KİM.10.2.4",
    zorluk: 3,
    soru: "20 °C'de KNO₃'ün çözünürlüğü 32 g/100 g sudur. 50 g suda en fazla kaç gram KNO₃ çözünür?",
    aciklama: "100 g suda 32 g çözünüyorsa 50 g suda yarısı, yani 16 g çözünür.",
    secenekler: ["16 g", "32 g", "8 g", "64 g"],
    dogru: 0,
  },
  {
    kod: "KİM.10.2.5",
    zorluk: 2,
    soru: "Katıların çoğunun sudaki çözünürlüğü sıcaklık arttıkça genellikle nasıl değişir?",
    aciklama: "Çoğu katının çözünürlüğü endotermik olduğu için sıcaklık arttıkça artar (ancak istisnalar vardır).",
    secenekler: ["Artar", "Azalır", "Değişmez", "Önce azalır sonra artar"],
    dogru: 0,
  },
  {
    kod: "KİM.10.2.5",
    zorluk: 3,
    soru: "Gazların sudaki çözünürlüğü basınç arttıkça nasıl değişir?",
    aciklama: "Henry yasasına göre gazların çözünürlüğü, üzerindeki kısmi basınçla doğru orantılıdır; basınç artarsa çözünürlük artar.",
    secenekler: ["Artar", "Azalır", "Değişmez", "Önce artar sonra azalır"],
    dogru: 0,
  },
  {
    kod: "KİM.10.2.6",
    zorluk: 2,
    soru: "Çözebileceği maksimum madde miktarını içeren çözeltiye ne denir?",
    aciklama: "Doygun çözelti, belirli sıcaklıkta çözebileceği en fazla çözüneni içerir; daha fazla çözünen eklenirse dibe çöker.",
    secenekler: ["Doygun çözelti", "Seyreltik çözelti", "Aşırı doygun çözelti", "Derişik çözelti"],
    dogru: 0,
  },
  {
    kod: "KİM.10.2.6",
    zorluk: 1,
    soru: "Deniz suyu hangi tür karışımdır?",
    aciklama: "Deniz suyu, tuzların suda çözünmesiyle oluşan homojen bir karışımdır (çözelti).",
    secenekler: ["Homojen karışım", "Heterojen karışım", "Süspansiyon", "Emülsiyon"],
    dogru: 0,
  },
  {
    kod: "KİM.10.2.7",
    zorluk: 3,
    soru: "0,5 mol NaCl 1 L suda çözülürse çözeltinin molar derişimi kaç molardır?",
    aciklama: "Molarite = mol / hacim(L) = 0,5 / 1 = 0,5 M.",
    secenekler: ["0,5 M", "1,0 M", "0,25 M", "2,0 M"],
    dogru: 0,
  },
  {
    kod: "KİM.10.2.7",
    zorluk: 3,
    soru: "2 M'lık 500 mL NaCl çözeltisinde kaç mol NaCl vardır?",
    aciklama: "mol = M × L = 2 × 0,5 = 1 mol.",
    secenekler: ["1 mol", "2 mol", "0,5 mol", "4 mol"],
    dogru: 0,
  },
  {
    kod: "KİM.10.2.8",
    zorluk: 3,
    soru: "Saf suya uçucu olmayan bir madde (ör. tuz) eklendiğinde suyun kaynama noktası nasıl değişir?",
    aciklama: "Çözünen tanecikler buhar basıncını düşürür, bu yüzden kaynama noktası yükselir (kaynama noktası yükselmesi).",
    secenekler: ["Yükselir", "Düşer", "Değişmez", "Önce düşer sonra yükselir"],
    dogru: 0,
  },
  {
    kod: "KİM.10.2.8",
    zorluk: 3,
    soru: "Kışın yollara tuz atılmasının nedeni aşağıdakilerden hangisidir?",
    aciklama: "Tuz, suyun donma noktasını düşürür (donma noktası alçalması), böylece buz oluşumu gecikir.",
    secenekler: [
      "Donma noktasını düşürmek",
      "Donma noktasını yükseltmek",
      "Kaynama noktasını düşürmek",
      "Buhar basıncını artırmak",
    ],
    dogru: 0,
  },

  // ===== 10.3 Sürdürülebilirlik (ek) =====
  {
    kod: "KİM.10.3.1",
    zorluk: 1,
    soru: "Mikro ölçekli deneylerin en önemli avantajı nedir?",
    aciklama: "Mikro ölçekli deneyler çok az kimyasal kullanır; bu sayede atık azalır, maliyet düşer ve güvenlik artar.",
    secenekler: [
      "Çok az kimyasal kullanarak atığı ve riski azaltmak",
      "Daha büyük alev kullanmak",
      "Daha çok kimyasal kullanmak",
      "Deney süresini uzatmak",
    ],
    dogru: 0,
  },
  {
    kod: "KİM.10.3.1",
    zorluk: 2,
    soru: "Mikro ölçekli deney tercih etmenin ekosistem açısından sonucu nedir?",
    aciklama: "Az kimyasal = az atık ve az kanalizasyona karışan madde; böylece su ve toprak kirliliği azalır.",
    secenekler: [
      "Su ve toprak kirliliği azalır",
      "Hava kirliliği artar",
      "Atık miktarı artar",
      "Ekosisteme hiçbir etkisi olmaz",
    ],
    dogru: 0,
  },
  {
    kod: "KİM.10.3.1",
    zorluk: 2,
    soru: "Aşağıdakilerden hangisi 'yeşil kimya'nın ilkelerinden biridir?",
    aciklama: "Yeşil kimya atık önleme, daha güvenli kimyasallar ve yenilenebilir hammadde kullanımı gibi ilkeleri benimser.",
    secenekler: ["Atık önleme", "Atık üretimini artırma", "Toksik madde kullanımı", "Enerji israfı"],
    dogru: 0,
  },
  {
    kod: "KİM.10.3.1",
    zorluk: 3,
    soru: "Bir öğrenci deneyde 100 mL yerine damlalıkla birkaç damla çözelti kullanırsa hangi davranışı sergilemiş olur?",
    aciklama: "Az miktarda madde ile deney yapmak mikro ölçekli çalışmadır; atık ve risk azalır.",
    secenekler: ["Mikro ölçekli çalışma", "Makro ölçekli çalışma", "Güvenli olmayan çalışma", "Endüstriyel çalışma"],
    dogru: 0,
  },
  {
    kod: "KİM.10.3.2",
    zorluk: 2,
    soru: "Asit yağmurlarının başlıca nedeni aşağıdakilerden hangisidir?",
    aciklama: "Fosil yakıtların yanmasıyla SO₂ ve NOₓ gazları açığa çıkar; bunlar atmosferde suyla birleşerek asit yağmurlarını oluşturur.",
    secenekler: [
      "SO₂ ve NOₓ gazlarının atmosferde suyla tepkimesi",
      "CO₂'nin fotosentezde kullanılması",
      "Ozonun oksijene dönüşmesi",
      "Su buharının yoğunlaşması",
    ],
    dogru: 0,
  },
  {
    kod: "KİM.10.3.2",
    zorluk: 2,
    soru: "Asit yağmurlarının ekosisteme etkisi aşağıdakilerden hangisidir?",
    aciklama: "Asit yağmurları toprağı ve suları asitleştirir; ormanlara, göllerdeki canlılara ve tarihî yapılara zarar verir.",
    secenekler: [
      "Toprağı ve suları asitleştirerek canlılara zarar verir",
      "Toprağın verimini her zaman artırır",
      "Sadece denizleri etkiler",
      "Canlılara hiçbir zararı yoktur",
    ],
    dogru: 0,
  },
  {
    kod: "KİM.10.3.2",
    zorluk: 1,
    soru: "Atmosferde sera etkisine en çok katkı yapan gazlardan biri hangisidir?",
    aciklama: "Karbondioksit (CO₂) başta olmak üzere metan ve su buharı sera gazlarıdır; fosil yakıt kullanımı CO₂'yi artırır.",
    secenekler: ["Karbondioksit (CO₂)", "Oksijen (O₂)", "Azot (N₂)", "Helyum (He)"],
    dogru: 0,
  },
  {
    kod: "KİM.10.3.2",
    zorluk: 2,
    soru: "Sera gazlarının artmasının küresel sonucu aşağıdakilerden hangisidir?",
    aciklama: "Sera gazları artınca atmosferde tutulan ısı artar; küresel sıcaklık yükselir (küresel ısınma), iklim değişikliğine yol açar.",
    secenekler: [
      "Küresel sıcaklığın artması",
      "Ozon tabakasının kalınlaşması",
      "Deniz seviyesinin düşmesi",
      "Buzulların büyümesi",
    ],
    dogru: 0,
  },
  {
    kod: "KİM.10.3.2",
    zorluk: 2,
    soru: "Kloroflorokarbonların (CFC) atmosferdeki temel zararı nedir?",
    aciklama: "CFC'ler ozon tabakasını inceltir; ozon tabakası zararlı UV ışınlarını süzer.",
    secenekler: [
      "Ozon tabakasını inceltmesi",
      "Oksijen üretmesi",
      "Asit yağmurunu durdurması",
      "Sera etkisini azaltması",
    ],
    dogru: 0,
  },
  {
    kod: "KİM.10.3.2",
    zorluk: 2,
    soru: "Fosil yakıt kullanımını azaltmak için aşağıdakilerden hangisi uygundur?",
    aciklama: "Güneş ve rüzgâr gibi yenilenebilir enerji kaynaklarına yönelmek fosil yakıt tüketimini ve emisyonları azaltır.",
    secenekler: [
      "Yenilenebilir enerji kaynaklarına yönelmek",
      "Kömür kullanımını artırmak",
      "Bireysel araç kullanımını artırmak",
      "Enerji tasarrufundan kaçınmak",
    ],
    dogru: 0,
  },
  {
    kod: "KİM.10.3.2",
    zorluk: 3,
    soru: "Fabrika bacalarına filtre takılması öncelikle hangi sorunu azaltır?",
    aciklama: "Filtreler SO₂, NOₓ ve partikül gibi kirleticilerin atmosfere salımını azaltır; böylece asit yağmuru ve hava kirliliği azalır.",
    secenekler: [
      "Asit yağmuru ve hava kirliliğini",
      "Ozon tabakası deliğini yalnızca",
      "Sera etkisini tamamen",
      "Hiçbir sorunu",
    ],
    dogru: 0,
  },
  {
    kod: "KİM.10.3.2",
    zorluk: 3,
    soru: "Karbon ayak izini azaltmak isteyen bir birey öncelikle hangisini yapmalıdır?",
    aciklama: "Toplu taşıma/bisiklet kullanımı ve enerji tasarrufu, fosil yakıt tüketimini ve dolayısıyla CO₂ salımını azaltır.",
    secenekler: [
      "Toplu taşıma ve enerji tasarrufuna yönelmek",
      "Tek kullanımlık plastik tüketimini artırmak",
      "Benzinli aracı daha çok kullanmak",
      "Isı yalıtımını azaltmak",
    ],
    dogru: 0,
  },
];
