// Tamamlayıcı soru bankası (11. sınıf): her ünitede en az 15 soru hedefi için ek sorular.
// seed-questions.ts tarafından import edilir (idempotent: prompt eşleşmesiyle tekrar eklenmez).

import type { SoruKayit } from "./questions-bank-extra";

export const EK_SORULAR_DOLDUR_11: SoruKayit[] = [
  // ===== U10 Enerji (KİM.11.1.1 +1, 11.1.2 +1, 11.1.3 +1, 11.1.4 +1, 11.1.6 +1) =====
  {
    kod: "KİM.11.1.1",
    zorluk: 2,
    soru: "Amonyum nitrat (NH₄NO₃) suda çözünürken kabın dış yüzeyi belirgin biçimde soğur. Bu gözlem için hangisi söylenir?",
    aciklama: "Kabın soğuması, çözünme sırasında ortamdan ısı alındığını gösterir. NH₄NO₃'ün çözünmesi endotermiktir; bu özelliğinden acil soğutma paketlerinde yararlanılır.",
    secenekler: [
      "Çözünme olayı endotermiktir (ortamdan ısı alınır)",
      "Çözünme olayı ekzotermiktir",
      "Çözünme sırasında ortama ısı verilir",
      "Olay sırasında enerji değişimi olmaz",
    ],
    dogru: 0,
  },
  {
    kod: "KİM.11.1.2",
    zorluk: 2,
    soru: "Doğal gazın ocakta yakıt olarak kullanılması, doğal gazın hangi özelliğinden yararlanıldığını gösterir?",
    aciklama: "Yakıtlardan, yanma tepkimeleri sırasında açığa çıkan ısıdan (ekzotermik yanma) yararlanılır. Doğal gaz yandığında yüksek miktarda ısı verir.",
    secenekler: [
      "Yanma tepkimesinin yüksek ısı vermesi (ekzotermik olması)",
      "Gazın renksiz olması",
      "Gazın havadan hafif olması",
      "Gazın kokusuz olması",
    ],
    dogru: 0,
  },
  {
    kod: "KİM.11.1.3",
    zorluk: 3,
    soru: "Bir tepkimede kırılan bağların enerjileri toplamı, oluşan bağların enerjileri toplamından büyükse tepkime için ne söylenir?",
    aciklama: "Bağ kırmak enerji ister, bağ oluşumu enerji verir. Kırılan bağ enerjisi oluşandan büyükse net enerji gerekir; tepkime endotermiktir (ΔH > 0).",
    secenekler: [
      "Endotermiktir (ısı alır)",
      "Ekzotermiktir",
      "Ortama ısı verir",
      "Kendiliğinden gerçekleşir",
    ],
    dogru: 0,
  },
  {
    kod: "KİM.11.1.4",
    zorluk: 2,
    soru: "Elementlerin en kararlı hâllerinin standart oluşum entalpisi (ΔH°f) için hangisi doğrudur?",
    aciklama: "Standart oluşum entalpisi tanımı gereği, elementlerin en kararlı hâllerinde (25 °C, 1 atm) ΔH°f değeri sıfır kabul edilir. Örneğin O₂(g) için ΔH°f = 0'dır.",
    secenekler: [
      "Sıfırdır",
      "Her element için farklı pozitif değer alır",
      "Yalnızca metalik elementlerde sıfırdır",
      "Deneysel olarak ölçülemez",
    ],
    dogru: 0,
  },
  {
    kod: "KİM.11.1.6",
    zorluk: 2,
    soru: "Bir tepkimenin hız-zaman grafiğinde zamanla hızın düşmesinin temel nedeni nedir?",
    aciklama: "Tepkime ilerledikçe girenlerin derişimi azalır, tanecikler arası çarpışma sayısı düşer ve tepkime hızı azalır. Ürün derişiminin artması hızı azaltmaz.",
    secenekler: [
      "Giren taneciklerinin derişiminin azalması",
      "Ürünlerin derişiminin azalması",
      "Sıcaklığın kendiliğinden artması",
      "Katalizörün etkisizleşmesi",
    ],
    dogru: 0,
  },
  // ===== U11 Kimyasal Tepkimelerde Hız (KİM.11.1.5 +3, 11.1.7 +3, 11.1.8 +3) =====
  {
    kod: "KİM.11.1.5",
    zorluk: 2,
    soru: "Oda sıcaklığında birbirine temas ettirildiğinde tepkime vermeyen iki katı, ısıtıldığında tepkimeye başlıyor. Bu gözlem hangisini gösterir?",
    aciklama: "Tepkimenin başlaması için taneciklerin aktivasyon enerjisi denilen minimum enerjiye ulaşması gerekir. Isıtma, taneciklere bu enerjiyi kazandırır.",
    secenekler: [
      "Taneciklerin tepkimeye girebilmesi için aktivasyon enerjisine ulaşması gerekir",
      "Tepkimeler yalnızca gaz fazında gerçekleşir",
      "Katılar hiçbir koşulda tepkime vermez",
      "Aktivasyon enerjisi tepkimeler için gerekli değildir",
    ],
    dogru: 0,
  },
  {
    kod: "KİM.11.1.5",
    zorluk: 1,
    soru: "Kibritin sürtünme yüzeyine sürtülerek çakılmasının temel amacı nedir?",
    aciklama: "Sürtünme, kibritin yanma tepkimesini başlatmak için gereken aktivasyon enerjisini sağlar. Tepkime başlayınca açığa çıkan ısı tepkimeyi sürdürür.",
    secenekler: [
      "Tepkimeyi başlatmak için gereken aktivasyon enerjisini sağlamak",
      "Kibritin kütlesini azaltmak",
      "Havadaki oksijeni kibritten uzaklaştırmak",
      "Kibriti nemlendirmek",
    ],
    dogru: 0,
  },
  {
    kod: "KİM.11.1.5",
    zorluk: 2,
    soru: "Tepkimeye giren taneciklerin yeterli enerjiyle ve uygun yönelimle çarpışmasına ne ad verilir?",
    aciklama: "Her çarpışma ürün oluşturmaz. Yeterli enerjiye sahip ve doğru yönelimde gerçekleşen çarpışmalara etkin çarpışma denir; yalnızca bu çarpışmalar tepkimeye yol açar.",
    secenekler: ["Etkin çarpışma", "Esnek çarpışma", "Zayıf çarpışma", "Denge çarpışması"],
    dogru: 0,
  },
  {
    kod: "KİM.11.1.7",
    zorluk: 2,
    soru: "Mermer parçaları (CaCO₃) ile HCl tepkimesinde asidin derişimi artırılırsa tepkime hızı nasıl değişir?",
    aciklama: "Derişim artarsa birim hacimdeki tanecik sayısı artar, çarpışma sayısı ve tepkime hızı artar.",
    secenekler: ["Artar", "Azalır", "Değişmez", "Önce azalır sonra artar"],
    dogru: 0,
  },
  {
    kod: "KİM.11.1.7",
    zorluk: 2,
    soru: "Bir tepkime karışımı ısıtıldığında tepkime hızının artmasının temel nedeni nedir?",
    aciklama: "Sıcaklık artışı taneciklerin ortalama kinetik enerjisini artırır; etkin çarpışma sayısı ve tepkime hızı artar.",
    secenekler: [
      "Taneciklerin ortalama kinetik enerjisi artar, etkin çarpışma sayısı artar",
      "Taneciklerin büyüklüğü artar",
      "Girenlerin derişimi kendiliğinden artar",
      "Katalizör oluşur",
    ],
    dogru: 0,
  },
  {
    kod: "KİM.11.1.7",
    zorluk: 3,
    soru: "Gaz fazındaki bir tepkimede kabın hacmi küçültülürse (basınç artarsa) tepkime hızının artmasının nedeni nedir?",
    aciklama: "Hacim küçülünce birim hacimdeki tanecik sayısı (derişim) artar; tanecikler birbirine yaklaşır ve çarpışma sayısı artar, dolayısıyla hız artar.",
    secenekler: [
      "Tanecikler birbirine yaklaşır, birim hacimdeki çarpışma sayısı artar",
      "Gazların molar kütlesi değişir",
      "Taneciklerin ortalama enerjisi artar",
      "Aktivasyon enerjisi düşer",
    ],
    dogru: 0,
  },
  {
    kod: "KİM.11.1.8",
    zorluk: 2,
    soru: "Hız ifadesi v = k[A][B] olan bir tepkimede A'nın derişimi iki katına çıkarılırsa (B sabit) tepkime hızı nasıl değişir?",
    aciklama: "A'nın üssü 1 olduğu için hız, A derişimiyle doğru orantılıdır. A iki katına çıkarsa hız da iki katına çıkar.",
    secenekler: ["İki katına çıkar", "Yarıya iner", "Dört katına çıkar", "Değişmez"],
    dogru: 0,
  },
  {
    kod: "KİM.11.1.8",
    zorluk: 3,
    soru: "Hız ifadesi v = k[A]² olan bir tepkimede A'nın derişimi 3 katına çıkarılırsa tepkime hızı kaç katına çıkar?",
    aciklama: "A'nın üssü 2 olduğundan hız, derişimin karesiyle orantılıdır: 3² = 9. Hız 9 katına çıkar.",
    secenekler: ["9", "3", "6", "27"],
    dogru: 0,
  },
  {
    kod: "KİM.11.1.8",
    zorluk: 3,
    soru: "2NO + O₂ → 2NO₂ tepkimesi için deneysel hız ifadesi v = k[NO]²[O₂]'dir. NO derişimi iki katına çıkarılırsa hız kaç katına çıkar?",
    aciklama: "NO'nun üssü 2 olduğundan hız, NO derişiminin karesiyle orantılıdır: 2² = 4. Hız 4 katına çıkar.",
    secenekler: ["4", "2", "8", "Değişmez"],
    dogru: 0,
  },
  // ===== U12 Denge (KİM.11.2.1 +2, 11.2.2 +2, 11.2.3 +2, 11.2.4 +2, 11.2.5 +1) =====
  {
    kod: "KİM.11.2.1",
    zorluk: 1,
    soru: "Bir tepkime denklemindeki ⇌ (çift yönlü ok) ne anlama gelir?",
    aciklama: "Çift yönlü ok, tepkimenin hem ileri hem geri yönde gerçekleşebildiğini, yani tersinir olduğunu gösterir. Tek yönlü ok (→) ise tepkimenin tamamlandığını belirtir.",
    secenekler: [
      "Tepkimenin hem ileri hem geri yönde gerçekleşebildiğini gösterir",
      "Tepkimenin yalnızca ileri yönde ilerlediğini gösterir",
      "Tepkimenin hızının sıfır olduğunu gösterir",
      "Tepkimenin ısı alarak gerçekleştiğini gösterir",
    ],
    dogru: 0,
  },
  {
    kod: "KİM.11.2.1",
    zorluk: 2,
    soru: "Kapalı bir kapta ısıtılan CaCO₃ ayrışıyor; sıcaklık düşürüldüğünde oluşan maddeler tekrar CaCO₃ oluşturabiliyor. Bu tepkime için ne denir?",
    aciklama: "Koşullar değiştiğinde ürünlerin tekrar girenlere dönüşebildiği tepkimeler tersinir tepkimelerdir. CaCO₃'ün ısıtılmasıyla ayrışması tersinir bir tepkimedir.",
    secenekler: [
      "Tersinir tepkime",
      "Nötralleşme tepkimesi",
      "Yanma tepkimesi",
      "Sentez tepkimesi",
    ],
    dogru: 0,
  },
  {
    kod: "KİM.11.2.2",
    zorluk: 2,
    soru: "Dengede olan bir sisteme giren (reaktif) madde eklenirse denge hangi yöne kayar?",
    aciklama: "Le Chatelier ilkesine göre sistem, uygulanan değişikliği azaltacak yönde tepki verir. Giren eklenince denge, eklenen maddeyi tüketecek yönde (ürünler yönüne) kayar.",
    secenekler: [
      "Ürünler yönüne (sağa)",
      "Girenler yönüne (sola)",
      "Hiç kaymaz",
      "Önce sola sonra sağa kayar",
    ],
    dogru: 0,
  },
  {
    kod: "KİM.11.2.2",
    zorluk: 3,
    soru: "Dengedeki bir gaz tepkimesinde hacim artırılıp basınç azaltılırsa denge hangi tarafa kayar?",
    aciklama: "Basınç azaldığında sistem, basıncı artıracak yöne yani gaz mol sayısı fazla olan tarafa kayar (Le Chatelier ilkesi).",
    secenekler: [
      "Gaz mol sayısı daha fazla olan tarafa",
      "Gaz mol sayısı daha az olan tarafa",
      "Isı veren tarafa",
      "Denge hiç kaymaz",
    ],
    dogru: 0,
  },
  {
    kod: "KİM.11.2.3",
    zorluk: 2,
    soru: "A + 2B ⇌ C tepkimesi için denge sabiti (Kc) ifadesi aşağıdakilerden hangisidir?",
    aciklama: "Kc ifadesinde ürünlerin derişimleri paya, girenlerin derişimleri katsayıları kadar üs alınarak paydaya yazılır: Kc = [C] / ([A][B]²).",
    secenekler: [
      "[C] / ([A][B]²)",
      "[A][B]² / [C]",
      "[C] / ([A][B])",
      "[A][B] / [C]",
    ],
    dogru: 0,
  },
  {
    kod: "KİM.11.2.3",
    zorluk: 3,
    soru: "Denge sabiti (Kc) ifadesine saf katıların ve saf sıvıların yazılmamasının nedeni nedir?",
    aciklama: "Saf katı ve saf sıvıların derişimi (aktifliği) sabit kabul edilir; bu yüzden Kc ifadesinde yer almazlar. Örneğin CaCO₃(k) ⇌ CaO(k) + CO₂(g) için Kc = [CO₂]'dir.",
    secenekler: [
      "Derişimleri sabit kabul edilir",
      "Tepkimeye hiç katılmazlar",
      "Kütleleri ölçülemez",
      "Dengeyi etkilemezler",
    ],
    dogru: 0,
  },
  {
    kod: "KİM.11.2.4",
    zorluk: 3,
    soru: "Dengede olmayan bir sistemde anlık oranlar çarpımı Q, denge sabiti Kc'den büyükse (Q > Kc) denge hangi yöne kayar?",
    aciklama: "Q > Kc ise ürünler olması gerekenden fazladır; sistem dengeye ulaşmak için ürünleri tüketip girenleri artıracak yönde, yani sola kayar.",
    secenekler: [
      "Ürünlerden girenlere doğru (sola)",
      "Girenlerden ürünlere doğru (sağa)",
      "Denge kayması olmaz",
      "Önce sağa sonra sola kayar",
    ],
    dogru: 0,
  },
  {
    kod: "KİM.11.2.4",
    zorluk: 2,
    soru: "Bir sistemde hesaplanan Q değeri denge sabiti Kc'ye eşitse sistem için ne söylenir?",
    aciklama: "Q = Kc olduğunda sistem dengededir; ileri ve geri tepkime hızları eşittir ve derişimler zamanla değişmez.",
    secenekler: [
      "Sistem dengededir",
      "Sistem henüz dengeye ulaşmamıştır",
      "Ürün derişimi artmaya devam eder",
      "Tepkime tamamlanmıştır",
    ],
    dogru: 0,
  },
  {
    kod: "KİM.11.2.5",
    zorluk: 3,
    soru: "N₂ + 3H₂ ⇌ 2NH₃ tepkimesi ekzotermiktir. Dengedeki sisteme sıcaklık artışı uygulanırsa denge hangi yöne kayar?",
    aciklama: "Ekzotermik tepkimede ısı ürün gibidir. Sıcaklık artırılırsa sistem ısıyı azaltacak yöne, yani endotermik olan geri yöne (girenlere) kayar; NH₃ verimi düşer.",
    secenekler: [
      "Girenler yönüne (sola)",
      "Ürünler yönüne (sağa)",
      "Denge kayması olmaz",
      "NH₃ miktarı artar",
    ],
    dogru: 0,
  },
  // ===== U13 Asit ve Baz Çözeltilerinde Denge (KİM.11.2.6 +1, 11.2.7 +1, 11.2.8 +2, 11.2.9 +1, 11.2.10 +1, 11.2.11 +1, 11.2.12 +2) =====
  {
    kod: "KİM.11.2.6",
    zorluk: 2,
    soru: "25 °C'de saf sudaki H⁺ ve OH⁻ iyon derişimleri için hangisi doğrudur?",
    aciklama: "Saf su az da olsa iyonlaşır (otoiyonizasyon). 25 °C'de [H⁺] = [OH⁻] = 1×10⁻⁷ M'dir ve iyon çarpımı Kw = 1×10⁻¹⁴'tür.",
    secenekler: [
      "İkisi de 1×10⁻⁷ M'dir ve birbirine eşittir",
      "H⁺ derişimi OH⁻'den fazladır",
      "OH⁻ derişimi H⁺'den fazladır",
      "İkisi de sıfırdır, saf su iyonlaşmaz",
    ],
    dogru: 0,
  },
  {
    kod: "KİM.11.2.7",
    zorluk: 1,
    soru: "Arrhenius'a göre suda çözündüğünde OH⁻ iyonu oluşturan maddeye ne ad verilir?",
    aciklama: "Arrhenius'a göre asit suda H⁺, baz suda OH⁻ oluşturur. Örneğin NaOH suda Na⁺ ve OH⁻ iyonlarına ayrışır, bu yüzden bazdır.",
    secenekler: ["Baz", "Asit", "Tuz", "Oksit"],
    dogru: 0,
  },
  {
    kod: "KİM.11.2.8",
    zorluk: 2,
    soru: "0,1 M HCl çözeltisi ile 0,1 M CH₃COOH çözeltisi aynı derişimde olmasına rağmen HCl'nin pH değeri daha düşüktür. Bunun nedeni nedir?",
    aciklama: "HCl kuvvetli asittir ve suda tamamen iyonlaşır; CH₃COOH ise zayıf asittir, kısmen iyonlaşır. Bu yüzden eşit derişimde HCl çözeltisinde H⁺ derişimi daha yüksektir.",
    secenekler: [
      "HCl kuvvetli asittir, suda tamamen iyonlaşır",
      "CH₃COOH kuvvetli asittir",
      "HCl zayıf bir elektrolittir",
      "CH₃COOH suda tamamen iyonlaşır",
    ],
    dogru: 0,
  },
  {
    kod: "KİM.11.2.8",
    zorluk: 2,
    soru: "Kuvvetli bazlar için aşağıdakilerden hangisi doğrudur?",
    aciklama: "Kuvvetli bazlar suda tamamen iyonlaşır. Örneğin NaOH → Na⁺ + OH⁻ biçiminde tam ayrışır. NH₃ gibi zayıf bazlar ise kısmen iyonlaşır.",
    secenekler: [
      "Suda tamamen iyonlaşır (ör. NaOH)",
      "Suda çok az iyonlaşır",
      "Sulu çözeltileri asidik özellik gösterir",
      "H⁺ iyonu oluştururlar",
    ],
    dogru: 0,
  },
  {
    kod: "KİM.11.2.9",
    zorluk: 3,
    soru: "0,01 M HCl çözeltisinin pH değeri kaçtır?",
    aciklama: "HCl kuvvetli asit olduğundan [H⁺] = 1×10⁻² M'dir. pH = -log[H⁺] = -log(10⁻²) = 2'dir.",
    secenekler: ["2", "1", "12", "13"],
    dogru: 0,
  },
  {
    kod: "KİM.11.2.10",
    zorluk: 1,
    soru: "Asit ile bazın tepkimesinde H⁺ ile OH⁻ iyonları birleşerek öncelikle hangi maddeyi oluşturur?",
    aciklama: "Nötralleşme tepkimesinde asidin H⁺ iyonu ile bazın OH⁻ iyonu birleşerek suyu (H₂O) oluşturur; kalan iyonlar da tuzu meydana getirir.",
    secenekler: ["Su", "Hidrojen gazı", "Klor gazı", "Karbondioksit"],
    dogru: 0,
  },
  {
    kod: "KİM.11.2.11",
    zorluk: 2,
    soru: "Asit-baz titrasyonunda eşdeğerlik (dönüm) noktasını belirlemek için aşağıdakilerden hangisi kullanılır?",
    aciklama: "Titrasyonda renk değiştiren indikatörler (belirteçler), asidin bazla tam nötralleştiği dönüm noktasını gösterir. Örneğin fenolftalein bazik ortamda pembe renk alır.",
    secenekler: ["İndikatör (belirteç)", "Ateş", "Hassas terazi", "Manometre"],
    dogru: 0,
  },
  {
    kod: "KİM.11.2.12",
    zorluk: 2,
    soru: "Banyoda biriken kirecin (CaCO₃) temizlenmesi için aşağıdakilerden hangisi en uygundur?",
    aciklama: "Kireç (CaCO₃) bazik bir tuzdur ve asitlerle çözünür. Sirke gibi zayıf asitler kireci çözerek temizler (CO₂ gazı açığa çıkar).",
    secenekler: [
      "Sirke gibi asidik bir temizleyici",
      "Saf su",
      "Sabunlu su",
      "Nişasta çözeltisi",
    ],
    dogru: 0,
  },
  {
    kod: "KİM.11.2.12",
    zorluk: 2,
    soru: "Toprağı asidik olan bir bahçede pH'ı yükseltmek (asitliği azaltmak) için aşağıdakilerden hangisi kullanılabilir?",
    aciklama: "Asidik toprağı nötralize etmek için bazik maddeler kullanılır. Kireç (CaO, CaCO₃) toprağın pH'ını yükselten geleneksel bir tarım uygulamasıdır.",
    secenekler: [
      "Kireç (CaO / CaCO₃ gibi bazik madde)",
      "Sirke",
      "Sülfürik asit",
      "Tuz ruhu (HCl)",
    ],
    dogru: 0,
  },
  // ===== U14 Çözünürlük Dengesi (KİM.11.2.13 +5, 11.2.14 +6) =====
  {
    kod: "KİM.11.2.13",
    zorluk: 2,
    soru: "AgCl(k) ⇌ Ag⁺(suda) + Cl⁻(suda) dengesi için çözünürlük çarpımı (Kçç) ifadesi aşağıdakilerden hangisidir?",
    aciklama: "Kçç ifadesinde saf katı (AgCl) yer almaz; iyon derişimlerinin çarpımı yazılır: Kçç = [Ag⁺][Cl⁻].",
    secenekler: [
      "[Ag⁺][Cl⁻]",
      "[AgCl]",
      "[Ag⁺] / [Cl⁻]",
      "[Ag⁺][Cl⁻] / [AgCl]",
    ],
    dogru: 0,
  },
  {
    kod: "KİM.11.2.13",
    zorluk: 3,
    soru: "PbCl₂(k) ⇌ Pb²⁺(suda) + 2Cl⁻(suda) dengesinde tuzun çözünürlüğü s ise Kçç aşağıdakilerden hangisidir?",
    aciklama: "Çözünen her PbCl₂ için 1 Pb²⁺ ve 2 Cl⁻ oluşur: [Pb²⁺] = s, [Cl⁻] = 2s. Kçç = [Pb²⁺][Cl⁻]² = s·(2s)² = 4s³.",
    secenekler: ["4s³", "s²", "2s³", "8s³"],
    dogru: 0,
  },
  {
    kod: "KİM.11.2.13",
    zorluk: 2,
    soru: "Kçç ifadesinde saf katının (ör. AgCl(k)) yer almamasının nedeni nedir?",
    aciklama: "Saf katıların derişimi (aktifliği) sabit kabul edilir; bu yüzden denge ifadesine yazılmaz. Kçç yalnızca iyon derişimlerine bağlıdır.",
    secenekler: [
      "Saf katının derişimi sabit kabul edilir",
      "Katı hiç çözünmez",
      "Katının kütlesi ölçülemez",
      "Katı dengeyi hiç etkilemez",
    ],
    dogru: 0,
  },
  {
    kod: "KİM.11.2.13",
    zorluk: 2,
    soru: "Aynı formüle (AB) sahip iki tuzdan Kçç değeri büyük olanın çözünürlüğü için ne söylenir?",
    aciklama: "Aynı tipteki tuzlar için Kçç ne kadar büyükse çözünürlük de o kadar fazladır. Kçç, az çözünen tuzun doygun çözeltisindeki iyon derişimleriyle belirlenir.",
    secenekler: [
      "Çözünürlüğü daha fazladır",
      "Çözünürlüğü daha azdır",
      "Çözünürlüğü aynıdır",
      "Çözünürlüğü sıcaklıkla ilişkisizdir",
    ],
    dogru: 0,
  },
  {
    kod: "KİM.11.2.13",
    zorluk: 3,
    soru: "AB₂ formülündeki bir tuzun saf sudaki çözünürlüğü 1×10⁻⁴ M ise Kçç değeri kaçtır?",
    aciklama: "AB₂(k) ⇌ A²⁺ + 2B⁻ dengesinde [A²⁺] = s ve [B⁻] = 2s'tir. Kçç = s·(2s)² = 4s³ = 4×(1×10⁻⁴)³ = 4×10⁻¹².",
    secenekler: ["4×10⁻¹²", "1×10⁻⁸", "1×10⁻¹²", "2×10⁻⁴"],
    dogru: 0,
  },
  {
    kod: "KİM.11.2.14",
    zorluk: 2,
    soru: "Doymuş AgCl çözeltisine AgNO₃ eklenirse AgCl'nin çözünürlüğü nasıl değişir?",
    aciklama: "AgNO₃, Ag⁺ iyonu sağlar (ortak iyon). Ortak iyon derişimi artınca denge katı yönüne kayar ve AgCl'nin çözünürlüğü azalır (ortak iyon etkisi).",
    secenekler: [
      "Azalır (ortak iyon etkisi)",
      "Artar",
      "Değişmez",
      "Önce artar sonra azalır",
    ],
    dogru: 0,
  },
  {
    kod: "KİM.11.2.14",
    zorluk: 2,
    soru: "Çözünmesi ekzotermik olan bir tuzun çözünürlüğü, sıcaklık artırılırsa nasıl değişir?",
    aciklama: "Ekzotermik çözünmede ısı ürün gibidir. Sıcaklık artırılırsa (ısı eklenirse) denge girenler yönüne kayar ve tuzun çözünürlüğü azalır (Le Chatelier ilkesi).",
    secenekler: ["Azalır", "Artar", "Değişmez", "Önce azalır sonra artar"],
    dogru: 0,
  },
  {
    kod: "KİM.11.2.14",
    zorluk: 3,
    soru: "Doymuş CaF₂ çözeltisine NaF eklenirse çözeltideki Ca²⁺ iyon derişimi nasıl değişir?",
    aciklama: "NaF, F⁻ iyonu sağlar (ortak iyon). Denge CaF₂(k) yönüne kayar, Ca²⁺ derişimi azalır: CaF₂(k) ⇌ Ca²⁺ + 2F⁻.",
    secenekler: ["Azalır", "Artar", "Değişmez", "Sıfır olur"],
    dogru: 0,
  },
  {
    kod: "KİM.11.2.14",
    zorluk: 2,
    soru: "Ortak iyon etkisi aşağıdaki ilkelerden hangisiyle açıklanır?",
    aciklama: "Ortak iyon eklenmesi, çözünürlük dengesini katı yönüne kaydırır. Bu davranış Le Chatelier ilkesinin bir uygulamasıdır.",
    secenekler: [
      "Le Chatelier ilkesi",
      "Pauli dışlama ilkesi",
      "Avogadro yasası",
      "Charles yasası",
    ],
    dogru: 0,
  },
  {
    kod: "KİM.11.2.14",
    zorluk: 3,
    soru: "25 °C'de AgCl'nin Kçç değeri 1,6×10⁻¹⁰ olduğuna göre AgCl'nin saf sudaki çözünürlüğü kaç mol/L'dir?",
    aciklama: "AgCl(k) ⇌ Ag⁺ + Cl⁻ olduğundan s = √Kçç = √(1,6×10⁻¹⁰) = 1,26×10⁻⁵ mol/L'dir.",
    secenekler: ["1,26×10⁻⁵", "1,6×10⁻¹⁰", "4×10⁻⁵", "3,2×10⁻¹⁰"],
    dogru: 0,
  },
  {
    kod: "KİM.11.2.14",
    zorluk: 2,
    soru: "Doymuş bir çözeltiye ortak iyon eklenmesi Kçç değerini nasıl etkiler?",
    aciklama: "Kçç yalnızca sıcaklığa bağlıdır; sabit sıcaklıkta ortak iyon eklenmesi Kçç'yi değiştirmez, yalnızca denge konumunu (çözünürlüğü) değiştirir.",
    secenekler: [
      "Değiştirmez; yalnızca denge konumunu değiştirir",
      "Küçültür",
      "Büyütür",
      "Sıfırlar",
    ],
    dogru: 0,
  },
];
