// Ek soru bankası — tüm ünitelerde quiz/kaçış/düello için en az 3 soru.
// seed-questions.ts tarafından import edilir.

export type SoruKayit = {
  kod: string;
  zorluk: number;
  soru: string;
  aciklama: string;
  secenekler: string[];
  dogru: number;
};

export const EK_SORULAR: SoruKayit[] = [
  // ===== 9.2 Etkileşimler =====
  {
    kod: "KİM.9.2.1",
    zorluk: 2,
    soru: "Metalik bağda elektronlar nasıl davranır?",
    aciklama: "Metalik bağda valans elektronları serbestçe hareket eden negatif yüklü elektron denizi oluşturur.",
    secenekler: [
      "Serbest elektron denizi oluşturur",
      "İki atom arasında tek çift paylaşılır",
      "Tamamen bir atoma transfer olur",
      "Sadece çekirdekler arasında kalır",
    ],
    dogru: 0,
  },
  {
    kod: "KİM.9.2.2",
    zorluk: 2,
    soru: "NaCl (sodyum klorür) oluşurken hangi bağ türü kurulur?",
    aciklama: "Na elektron vererek Na⁺, Cl elektron alarak Cl⁻ olur; zıt yüklü iyonlar arasında iyonik bağ oluşur.",
    secenekler: ["İyonik bağ", "Kovalent bağ", "Metalik bağ", "Hidrojen bağı"],
    dogru: 0,
  },
  {
    kod: "KİM.9.2.3",
    zorluk: 2,
    soru: "H₂ molekülünde hidrojen atomları arasında hangi bağ vardır?",
    aciklama: "Aynı ametal atomları elektronlarını ortaklaşa kullanarak kovalent bağ oluşturur.",
    secenekler: ["Kovalent bağ", "İyonik bağ", "Metalik bağ", "Van der Waals"],
    dogru: 0,
  },
  {
    kod: "KİM.9.2.4",
    zorluk: 3,
    soru: "H₂O molekülünün Lewis nokta yapısında oksijen atomunda kaç ortaklanmamış elektron çifti vardır?",
    aciklama: "Oksijen 2 hidrojenle tekli bağ yapar; kalan 2 elektron çifti ortaklanmamış çift olarak kalır.",
    secenekler: ["2", "0", "1", "4"],
    dogru: 0,
  },
  {
    kod: "KİM.9.2.5",
    zorluk: 2,
    soru: "CO₂ molekülü polar mı apolar mıdır?",
    aciklama: "CO₂ doğrusal yapıdadır; C=O dipolları birbirini iptal eder → apolar molekül.",
    secenekler: ["Apolar", "Polar", "İyonik", "Metalik"],
    dogru: 0,
  },
  {
    kod: "KİM.9.2.6",
    zorluk: 2,
    soru: "CaCl₂ bileşiğinin adı aşağıdakilerden hangisidir?",
    aciklama: "Ca²⁺ ve Cl⁻ iyonlarından oluşan iyonik bileşik: kalsiyum klorür.",
    secenekler: ["Kalsiyum klorür", "Kalsiyum klorat", "Kalsiyum oksit", "Kalsiyum hidroksit"],
    dogru: 0,
  },
  // ===== 9.2 Etkileşimden Maddeye =====
  {
    kod: "KİM.9.2.7",
    zorluk: 2,
    soru: "H₂O molekülleri arasında baskın etkileşim hangisidir?",
    aciklama: "Su molekülleri polar olduğu için aralarında hidrojen bağı oluşur.",
    secenekler: ["Hidrojen bağı", "Metalik bağ", "İyonik bağ", "Sadece London kuvveti"],
    dogru: 0,
  },
  {
    kod: "KİM.9.2.8",
    zorluk: 2,
    soru: "Elmasın çok sert olmasının temel nedeni nedir?",
    aciklama: "Elmasta karbon atomları güçlü kovalent ağ yapısı oluşturur; bu yapı sertlik verir.",
    secenekler: ["Güçlü kovalent ağ yapısı", "Metalik bağ", "Zayıf moleküller arası kuvvet", "İyonik yapı"],
    dogru: 0,
  },
  {
    kod: "KİM.9.2.9",
    zorluk: 2,
    soru: "Aynı sıcaklıkta buhar basıncı en yüksek olan sıvı hangi özelliğe sahiptir?",
    aciklama: "Buhar basıncı yüksek olan sıvılar genellikle uçucudur; moleküller kolayca buharlaşır.",
    secenekler: ["Daha uçucu", "Daha viskoz", "Daha yoğun", "Daha az polar"],
    dogru: 0,
  },
  {
    kod: "KİM.9.2.10",
    zorluk: 3,
    soru: "Aynı moleküler yapıda H₂O ve H₂S karşılaştırıldığında kaynama noktası neden farklıdır?",
    aciklama: "H₂O molekülleri arasında güçlü hidrojen bağı vardır; H₂S'te daha zayıf etkileşim → H₂O daha yüksek kaynar.",
    secenekler: [
      "H₂O'da hidrojen bağı daha güçlüdür",
      "H₂S daha polar bir moleküldür",
      "H₂O iyonik yapıdadır",
      "H₂S daha ağır moleküldür",
    ],
    dogru: 0,
  },
  {
    kod: "KİM.9.2.11",
    zorluk: 2,
    soru: "Bal viskoz, su akışkandır. Bu farkı en iyi açıklayan kavram hangisidir?",
    aciklama: "Viskozite sıvının akış direncidir; balda moleküller arası etkileşimler daha güçlüdür.",
    secenekler: ["Viskozite", "Buhar basıncı", "Yoğunluk", "Yüzey gerilimi"],
    dogru: 0,
  },
  {
    kod: "KİM.9.2.12",
    zorluk: 2,
    soru: "Cam bir boruda su yükselmesi (kılcallık) hangi kuvvetlerle açıklanır?",
    aciklama: "Adezyon (su-cam) kohezyondan (su-su) güçlü olduğunda kılcallık artar.",
    secenekler: ["Adezyon > kohezyon", "Kohezyon > adezyon", "Sadece yerçekimi", "Metalik bağ"],
    dogru: 0,
  },
  {
    kod: "KİM.9.2.13",
    zorluk: 2,
    soru: "Sabunlu suda böcek ayaklarının batmaması hangi özellikle ilgilidir?",
    aciklama: "Sabun yüzey gerilimini azaltır; suyun yüzeyinde durma kolaylaşır.",
    secenekler: ["Yüzey geriliminin azalması", "Viskozitenin artması", "Buhar basıncı", "İyonlaşma"],
    dogru: 0,
  },
  // ===== 9.3 Sürdürülebilirlik =====
  {
    kod: "KİM.9.3.1",
    zorluk: 2,
    soru: "Yeşil kimyanın atık önleme ilkesi ne anlama gelir?",
    aciklama: "Atık önleme, atığı sonradan temizlemek yerine kaynağında azaltmayı hedefler.",
    secenekler: [
      "Atığı kaynağında azaltmak",
      "Atığı denize boşaltmak",
      "Daha fazla kimyasal kullanmak",
      "Atığı yakmak",
    ],
    dogru: 0,
  },
  {
    kod: "KİM.9.3.2",
    zorluk: 2,
    soru: "Ağır metallerin ekosistemde birikmesi hangi soruna yol açar?",
    aciklama: "Ağır metaller besin zincirinde birikerek canlılarda zehirlenmeye neden olabilir.",
    secenekler: ["Besin zincirinde birikme ve zehirlenme", "Ozon tabakasının kalınlaşması", "Su buharlaşmasının durması", "Fotosentezin artması"],
    dogru: 0,
  },
  {
    kod: "KİM.9.3.1",
    zorluk: 3,
    soru: "Nanoparçacıkların boyutu küçüldükçe hangi özellik değişebilir?",
    aciklama: "Nanometre ölçeğinde yüzey/hacim oranı artar; tepkime hızı ve etkinlik değişebilir.",
    secenekler: ["Yüzey/hacim oranı artar", "Kütle sıfır olur", "Renk her zaman sabittir", "Kimyasal yapı tamamen kaybolur"],
    dogru: 0,
  },
  // ===== 10.1 Kimyasal Tepkimeler =====
  {
    kod: "KİM.10.1.1",
    zorluk: 2,
    soru: "Aşağıdakilerden hangisi kimyasal değişimin göstergesidir?",
    aciklama: "Renk değişimi, gaz çıkışı, çökelme veya ısı alışverişi kimyasal değişim göstergesidir.",
    secenekler: ["Gaz kabarcığı oluşması", "Sadece erime", "Parçacık boyutunun küçülmesi", "Fiziksel karışım"],
    dogru: 0,
  },
  {
    kod: "KİM.10.1.2",
    zorluk: 2,
    soru: "2H₂ + O₂ → 2H₂O tepkimesinde hangi yasa korunur?",
    aciklama: "Kimyasal tepkimelerde atom türleri ve sayıları korunur (kütlenin korunumu).",
    secenekler: ["Kütlenin korunumu", "Hacmin her zaman artması", "Enerjinin yok olması", "Proton sayısının değişmesi"],
    dogru: 0,
  },
  {
    kod: "KİM.10.1.3",
    zorluk: 2,
    soru: "HCl + NaOH → NaCl + H₂O tepkimesi hangi türdendir?",
    aciklama: "Asit ve baz tuz + su oluşturur → nötrleşme (asit-baz) tepkimesi.",
    secenekler: ["Asit-baz (nötrleşme)", "Yanma", "Sentez", "Ayrışma"],
    dogru: 0,
  },
  {
    kod: "KİM.10.1.4",
    zorluk: 2,
    soru: "1 mol su (H₂O) kaç gramdır? (H:1, O:16 g/mol)",
    aciklama: "Molar kütle = 2×1 + 16 = 18 g/mol.",
    secenekler: ["18 g", "16 g", "2 g", "36 g"],
    dogru: 0,
  },
  {
    kod: "KİM.10.1.5",
    zorluk: 3,
    soru: "Fe + O₂ → Fe₂O₃ denklemi dengelenince Fe katsayısı kaç olur?",
    aciklama: "4Fe + 3O₂ → 2Fe₂O₃",
    secenekler: ["4", "2", "1", "3"],
    dogru: 0,
  },
  // ===== 10.1 Gazlar =====
  {
    kod: "KİM.10.1.8",
    zorluk: 2,
    soru: "Kinetik moleküler teoriye göre gaz molekülleri nasıl hareket eder?",
    aciklama: "Gaz molekülleri düzensiz, hızlı ve sürekli hareket halindedir.",
    secenekler: ["Düzensiz ve hızlı hareket", "Sabit konumda titreşim", "Düzenli kristal ağ", "Sadece aşağı düşer"],
    dogru: 0,
  },
  {
    kod: "KİM.10.1.9",
    zorluk: 2,
    soru: "Sabit sıcaklıkta gaz hacmi basınçla ters orantılıdır. Bu hangi yasadır?",
    aciklama: "Boyle yasası: P × V = sabit (T sabit).",
    secenekler: ["Boyle yasası", "Charles yasası", "Avogadro yasası", "Dalton yasası"],
    dogru: 0,
  },
  {
    kod: "KİM.10.1.10",
    zorluk: 3,
    soru: "İdeal gaz denklemi hangisidir?",
    aciklama: "PV = nRT ideal gaz denklemidir.",
    secenekler: ["PV = nRT", "P = mV", "V = m/n", "n = PT"],
    dogru: 0,
  },
  // ===== 10.2 Çözeltiler =====
  {
    kod: "KİM.10.2.1",
    zorluk: 2,
    soru: "Çözeltide çözünen maddeye ne denir?",
    aciklama: "Çözünen: çözeltiye katılan madde. Çözücü: daha fazla miktarda bulunan madde.",
    secenekler: ["Çözünen", "Çözücü", "Katalizör", "İndirgen"],
    dogru: 0,
  },
  {
    kod: "KİM.10.2.3",
    zorluk: 2,
    soru: "36 g su içinde 9 g tuz çözülmüştür. Kütlece % kaç tuz vardır?",
    aciklama: "% m/m = (9/45)×100 = %20",
    secenekler: ["%20", "%25", "%9", "%36"],
    dogru: 0,
  },
  {
    kod: "KİM.10.2.5",
    zorluk: 2,
    soru: "Doymuş çözelti ne demektir?",
    aciklama: "Belirli sıcaklıkta çözücü daha fazla çözünen alamaz → doymuş çözelti.",
    secenekler: [
      "O sıcaklıkta maksimum çözünen içerir",
      "Hiç çözünen yoktur",
      "Sonsuz çözünen alabilir",
      "Sadece gaz içerir",
    ],
    dogru: 0,
  },
  // ===== 10.3 Sürdürülebilirlik =====
  {
    kod: "KİM.10.3.1",
    zorluk: 2,
    soru: "Yeşil kimyanın temel amacı nedir?",
    aciklama: "Yeşil kimya çevresel etkiyi azaltarak sürdürülebilir üretim hedefler.",
    secenekler: [
      "Çevresel etkiyi azaltmak",
      "Daha fazla atık üretmek",
      "Tehlikeli maddeleri artırmak",
      "Enerji tüketimini artırmak",
    ],
    dogru: 0,
  },
  {
    kod: "KİM.10.3.2",
    zorluk: 2,
    soru: "Atom ekonomisi yüksek tepkime ne anlama gelir?",
    aciklama: "Başlangıç maddelerinin büyük kısmı istenen ürüne dönüşür; atık azdır.",
    secenekler: ["Az yan ürün, yüksek verim", "Çok atık", "Enerji kaybı", "Katalizör yok"],
    dogru: 0,
  },
  {
    kod: "KİM.10.3.1",
    zorluk: 3,
    soru: "Sürdürülebilir kalkınma hedeflerinden biri temiz su ve sanitasyon hangi numaradır?",
    aciklama: "BM SKH 6: Temiz su ve sanitasyon.",
    secenekler: ["6", "12", "14", "1"],
    dogru: 0,
  },
  // ===== 11.1 Enerji =====
  {
    kod: "KİM.11.1.1",
    zorluk: 2,
    soru: "Ekzotermik tepkimede sistem çevresine ne verir?",
    aciklama: "Ekzotermik: sistem ısı verir (ΔH < 0).",
    secenekler: ["Isı verir", "Isı alır", "Işık emer", "Kütle kaybeder"],
    dogru: 0,
  },
  {
    kod: "KİM.11.1.2",
    zorluk: 2,
    soru: "Endotermik tepkimenin entalpi değişimi (ΔH) genellikle nasıldır?",
    aciklama: "Endotermik tepkimeler ısı alır → ΔH pozitiftir.",
    secenekler: ["Pozitif", "Sıfır", "Her zaman negatif", "Tanımsız"],
    dogru: 0,
  },
  {
    kod: "KİM.11.1.3",
    zorluk: 2,
    soru: "Hess yasası neyi ifade eder?",
    aciklama: "Toplam entalpi değişimi yol bağımsızdır; ara basamakların ΔH toplamına eşittir.",
    secenekler: [
      "Entalpi değişimi yol bağımsızdır",
      "Tüm tepkimeler ekzotermiktir",
      "Basınç sabittir",
      "Katalizör entalpiyi değiştirir",
    ],
    dogru: 0,
  },
  // ===== 11.1 Kimyasal Tepkimelerde Hız =====
  {
    kod: "KİM.11.1.5",
    zorluk: 2,
    soru: "Tepkime hızını artırmak için genellikle hangisi yapılır?",
    aciklama: "Sıcaklık artışı moleküllerin ortalama kinetik enerjisini artırır → daha fazla etkin çarpışma.",
    secenekler: ["Sıcaklığı artırmak", "Katalizörü çıkarmak", "Derişimi azaltmak", "Yüzey alanını küçültmek"],
    dogru: 0,
  },
  {
    kod: "KİM.11.1.6",
    zorluk: 2,
    soru: "Katalizör tepkime hızını nasıl etkiler?",
    aciklama: "Katalizör aktivasyon enerjisini düşürür; denge konumunu değiştirmez.",
    secenekler: ["Aktivasyon enerjisini düşürür", "ΔH'yi değiştirir", "Dengeyi kaydırır", "Tepkimeyi durdurur"],
    dogru: 0,
  },
  {
    kod: "KİM.11.1.7",
    zorluk: 3,
    soru: "Toz halindeki demirin çubuk demirden hızlı yanmasının nedeni nedir?",
    aciklama: "Küçük parçacık → büyük yüzey alanı → daha hızlı tepkime.",
    secenekler: ["Yüzey alanının artması", "Kütlenin azalması", "Basıncın düşmesi", "Katalizör yokluğu"],
    dogru: 0,
  },
  // ===== 11.2 Denge =====
  {
    kod: "KİM.11.2.1",
    zorluk: 2,
    soru: "Dinamik dengede hangisi doğrudur?",
    aciklama: "İleri ve geri tepkime hızları eşittir; makroskopik özellikler sabittir.",
    secenekler: [
      "İleri ve geri hız eşit",
      "Tepkime durmuştur",
      "Konsantrasyonlar sıfır",
      "Sadece ürün vardır",
    ],
    dogru: 0,
  },
  {
    kod: "KİM.11.2.2",
    zorluk: 2,
    soru: "Le Chatelier ilkesine göre dengedeki sisteme ürün eklenirse ne olur?",
    aciklama: "Sistem stresi azaltmak için geri yönde tepki verir (denge sola kayar).",
    secenekler: ["Geri yöne kayar", "İleri yöne kayar", "Değişmez", "Tepkime biter"],
    dogru: 0,
  },
  {
    kod: "KİM.11.2.3",
    zorluk: 2,
    soru: "Kp ifadesi hangi tür denge sabitidir?",
    aciklama: "Kp basınç cinsinden denge sabitidir; gaz fazı tepkimelerinde kullanılır.",
    secenekler: ["Basınç cinsinden denge sabiti", "Hız sabiti", "Mol sabiti", "Sıcaklık sabiti"],
    dogru: 0,
  },
  // ===== 11.2 Asit-Baz =====
  {
    kod: "KİM.11.2.5",
    zorluk: 2,
    soru: "pH = 3 olan çözelti için ne söylenir?",
    aciklama: "pH < 7 asidik; pH = 3 oldukça asidik bir ortamdır.",
    secenekler: ["Asidiktir", "Baziktir", "Nötrdür", "Tuzlu sudur"],
    dogru: 0,
  },
  {
    kod: "KİM.11.2.6",
    zorluk: 2,
    soru: "Brønsted-Lowry tanımına göre asit nedir?",
    aciklama: "Brønsted asidi: proton (H⁺) veren türdür.",
    secenekler: ["Proton veren", "Proton alan", "Elektron veren", "Elektron alan"],
    dogru: 0,
  },
  {
    kod: "KİM.11.2.7",
    zorluk: 3,
    soru: "Tampon çözeltinin özelliği nedir?",
    aciklama: "Tampon, az miktarda asit/baz eklendiğinde pH'yi büyük ölçüde sabit tutar.",
    secenekler: ["pH'yi büyük ölçüde sabit tutar", "Her zaman pH=7'dir", "Asit içermez", "Baz içermez"],
    dogru: 0,
  },
  // ===== 11.2 Çözünürlük Dengesi =====
  {
    kod: "KİM.11.2.9",
    zorluk: 2,
    soru: "Ksp (çözünürlük çarpımı sabiti) neyi ifade eder?",
    aciklama: "Ksp, doymuş çözeltide iyon konsantrasyonlarının çarpımını ifade eder.",
    secenekler: ["Doymuş çözeltide iyon çarpımı", "Tepkime hızı", "pH değeri", "Basınç"],
    dogru: 0,
  },
  {
    kod: "KİM.11.2.10",
    zorluk: 2,
    soru: "Ortak iyon etkisi çözünürlüğü nasıl etkiler?",
    aciklama: "Ortak iyon eklenince denge sola kayar → çözünürlük azalır.",
    secenekler: ["Azaltır", "Artırır", "Değiştirmez", "Sıfırlar"],
    dogru: 0,
  },
  {
    kod: "KİM.11.2.11",
    zorluk: 2,
    soru: "AgCl katısı suda az çözünür. Çözeltiye NaCl eklenirse AgCl çözünürlüğü?",
    aciklama: "Cl⁻ ortak iyon → AgCl(s) ⇌ Ag⁺ + Cl⁻ dengesi sola kayar.",
    secenekler: ["Azalır", "Artar", "Aynı kalır", "Sonsuz artar"],
    dogru: 0,
  },
  // ===== 11.3 Nanoteknoloji =====
  {
    kod: "KİM.11.3.1",
    zorluk: 2,
    soru: "Nanoteknoloji hangi boyut aralığında çalışır?",
    aciklama: "Nanoteknoloji genellikle 1–100 nm boyut aralığındaki yapılarla ilgilenir.",
    secenekler: ["1–100 nm", "1–100 cm", "1–100 m", "1–100 μm"],
    dogru: 0,
  },
  {
    kod: "KİM.11.3.2",
    zorluk: 2,
    soru: "Nano malzemelerin toksisitesi neden tartışılır?",
    aciklama: "Küçük boyut ve yüksek yüzey alanı biyolojik sistemlerde beklenmedik etkilere yol açabilir.",
    secenekler: ["Yüksek yüzey alanı ve biyouyumluluk", "Renkleri", "Kütlesi", "Erime noktası"],
    dogru: 0,
  },
  {
    kod: "KİM.11.3.3",
    zorluk: 2,
    soru: "Sürdürülebilir nanoteknoloji yaklaşımı neyi hedefler?",
    aciklama: "Fayda sağlarken çevresel ve sağlık risklerini minimize etmeyi hedefler.",
    secenekler: ["Fayda ve risk dengesi", "Sadece üretim hızı", "Atık artışı", "Enerji israfı"],
    dogru: 0,
  },
  // ===== 12.1 İndirgenme-Yükseltgenme =====
  {
    kod: "KİM.12.1.1",
    zorluk: 2,
    soru: "Yükseltgenme ne demektir?",
    aciklama: "Yükseltgenme: elektron kaybetme veya yükseltgenme basamağının artması.",
    secenekler: ["Elektron kaybetme", "Elektron alma", "Proton alma", "Nötron kaybetme"],
    dogru: 0,
  },
  {
    kod: "KİM.12.1.2",
    zorluk: 2,
    soru: "Redoks tepkimesinde indirgen madde ne yapar?",
    aciklama: "İndirgen: elektron vererek başka türü indirger (kendisi yükseltgenir).",
    secenekler: ["Elektron verir", "Elektron alır", "Proton verir", "Isı emer"],
    dogru: 0,
  },
  {
    kod: "KİM.12.1.3",
    zorluk: 3,
    soru: "Zn + Cu²⁺ → Zn²⁺ + Cu tepkimesinde indirgen hangisidir?",
    aciklama: "Zn elektron vererek Zn²⁺ olur → indirgen (yükseltgenir).",
    secenekler: ["Zn", "Cu²⁺", "Cu", "Zn²⁺"],
    dogru: 0,
  },
  // ===== 12.1 Elektrokimyasal Hücreler =====
  {
    kod: "KİM.12.1.5",
    zorluk: 2,
    soru: "Galvanik hücrede anot elektrotunda ne olur?",
    aciklama: "Anotta yükseltgenme (elektron kaybı) gerçekleşir.",
    secenekler: ["Yükseltgenme", "İndirgenme", "Nötrleşme", "Çökelme"],
    dogru: 0,
  },
  {
    kod: "KİM.12.1.6",
    zorluk: 2,
    soru: "Elektrolizde enerji kaynağı ne sağlar?",
    aciklama: "Elektrolizde dış gerilim kaynağı (batarya/güç) ile zorunlu redoks gerçekleşir.",
    secenekler: ["Dış gerilim kaynağı", "Sadece ısı", "Yerçekimi", "Manyetik alan"],
    dogru: 0,
  },
  {
    kod: "KİM.12.1.7",
    zorluk: 2,
    soru: "Standart hidrojen elektrodu (SHE) için E° değeri kaç kabul edilir?",
    aciklama: "Tanım gereği SHE için E° = 0,00 V alınır.",
    secenekler: ["0,00 V", "1,00 V", "-1,00 V", "2,00 V"],
    dogru: 0,
  },
  // ===== 12.2 Organik Kimyaya Giriş =====
  {
    kod: "KİM.12.2.1",
    zorluk: 2,
    soru: "Organik bileşiklerin temel yapı taşı hangi elementtir?",
    aciklama: "Organik kimya esas olarak karbon bileşiklerini inceler.",
    secenekler: ["Karbon", "Demir", "Sodyum", "Klor"],
    dogru: 0,
  },
  {
    kod: "KİM.12.2.2",
    zorluk: 2,
    soru: "Hidrokarbon nedir?",
    aciklama: "Hidrokarbonlar yalnızca karbon ve hidrojen içeren bileşiklerdir.",
    secenekler: ["C ve H içeren bileşik", "Sadece su", "Metal alaşım", "Tuz"],
    dogru: 0,
  },
  {
    kod: "KİM.12.2.3",
    zorluk: 2,
    soru: "CH₄ molekülü hangi hidrokarbon sınıfına girer?",
    aciklama: "CH₄ (metan) doymuş alkan (tekli bağlı hidrokarbon) sınıfındadır.",
    secenekler: ["Alkan", "Alken", "Alkin", "Aromatik"],
    dogru: 0,
  },
  // ===== 12.2 Organik Bileşikler =====
  {
    kod: "KİM.12.2.5",
    zorluk: 2,
    soru: "C₂H₄ (etilen) hangi fonksiyonel grup türüne örnektir?",
    aciklama: "Etilen çift bağ içerir → alken.",
    secenekler: ["Alken", "Alkan", "Alkol", "Karboksilli asit"],
    dogru: 0,
  },
  {
    kod: "KİM.12.2.6",
    zorluk: 2,
    soru: "C₂H₅OH hangi organik bileşik sınıfındadır?",
    aciklama: "Etanol (-OH grubu) alkol sınıfındadır.",
    secenekler: ["Alkol", "Eter", "Aldehit", "Ester"],
    dogru: 0,
  },
  {
    kod: "KİM.12.2.7",
    zorluk: 3,
    soru: "İzomer kavramı ne anlama gelir?",
    aciklama: "İzomerler aynı molekül formülüne sahip farklı yapısal bileşiklerdir.",
    secenekler: ["Aynı formül, farklı yapı", "Farklı formül, aynı yapı", "Aynı element", "Farklı atom"],
    dogru: 0,
  },
  // ===== 12.3 Nanobilim =====
  {
    kod: "KİM.12.3.1",
    zorluk: 2,
    soru: "Grafen hangi yapıya sahip tek katmanlı karbon malzemedir?",
    aciklama: "Grafen, tek atom kalınlığında altıgen hücreli karbon ağıdır.",
    secenekler: ["Altıgen karbon ağı", "Küp kristal", "Amorf yapı", "İyonik katı"],
    dogru: 0,
  },
  {
    kod: "KİM.12.3.2",
    zorluk: 2,
    soru: "Yeşil kimyada 'daha güvenli çözücüler' ilkesi neyi hedefler?",
    aciklama: "Toksik çözücülerin yerine çevre ve sağlık açısından daha güvenli alternatifler kullanmak.",
    secenekler: ["Toksik çözücüleri azaltmak", "Daha fazla VOC salmak", "Su kullanımını yasaklamak", "Plastik artırmak"],
    dogru: 0,
  },
  {
    kod: "KİM.12.3.3",
    zorluk: 2,
    soru: "Sürdürülebilir üretimde geri dönüşümün amacı nedir?",
    aciklama: "Ham madde ve enerji tüketimini azaltmak, atığı kaynağında önlemek.",
    secenekler: ["Kaynak tüketimini azaltmak", "Atığı artırmak", "Enerji israfı", "Tek kullanımlık artış"],
    dogru: 0,
  },
  // Ek sorular — mevcut 9.1 ünitelerine derinlik (farklı indeksler)
  {
    kod: "KİM.9.1.2",
    zorluk: 1,
    soru: "Evde kullanılan çamaşır suyu ile sirke karıştırılmamalıdır. Bunun nedeni?",
    aciklama: "Asit + hipoklorit → tehlikeli klor gazı açığa çıkabilir. Kimyasallar rastgele karıştırılmamalı.",
    secenekler: ["Tehlikeli gaz oluşabilir", "Renk güzelleşir", "Daha etkili olur", "Hiçbir şey olmaz"],
    dogru: 0,
  },
  {
    kod: "KİM.9.1.7",
    zorluk: 2,
    soru: "Cl atomu bir elektron aldığında hangi iyon oluşur?",
    aciklama: "Cl + e⁻ → Cl⁻ (klorür anyonu, 17 proton, 18 elektron).",
    secenekler: ["Cl⁻", "Cl⁺", "Cl²⁺", "Cl₂"],
    dogru: 0,
  },
  {
    kod: "KİM.9.1.5",
    zorluk: 2,
    soru: "Karbon atomunun (Z=6) yerleşmemiş elektron dizilimi hangisidir?",
    aciklama: "Karbon: 1s² 2s² 2p²",
    secenekler: ["1s² 2s² 2p²", "1s² 2s² 2p⁶", "1s² 2s¹", "1s² 2p⁴"],
    dogru: 0,
  },
  // Eksik üniteler — minimum 3 soru
  {
    kod: "KİM.11.1.8",
    zorluk: 3,
    soru: "Tepkime hızı v = k[A]²[B] ise bu tepkimenin toplam derecesi kaçtır?",
    aciklama: "Hız denklemindeki üslüler toplanır: 2 + 1 = 3.",
    secenekler: ["3", "2", "1", "5"],
    dogru: 0,
  },
  {
    kod: "KİM.11.1.8",
    zorluk: 2,
    soru: "Hız sabiti (k) hangi faktörlere bağlıdır?",
    aciklama: "k sıcaklık ve katalizöre bağlıdır; derişime doğrudan bağlı değildir (denklemde ayrı yazılır).",
    secenekler: ["Sıcaklık ve katalizör", "Yalnızca derişim", "Yalnızca basınç", "Zaman"],
    dogru: 0,
  },
  {
    kod: "KİM.11.2.13",
    zorluk: 2,
    soru: "CaF₂ ⇌ Ca²⁺ + 2F⁻ dengesinde Kçç ifadesi hangisidir?",
    aciklama: "Kçç = [Ca²⁺][F⁻]² (katı CaF₂ denkleme yazılmaz).",
    secenekler: ["[Ca²⁺][F⁻]²", "[Ca²⁺][F⁻]", "[CaF₂]", "1/[Ca²⁺]"],
    dogru: 0,
  },
  {
    kod: "KİM.11.2.13",
    zorluk: 2,
    soru: "Kçç değeri küçük olan tuz için ne söylenir?",
    aciklama: "Küçük Kçç → suda az çözünür (düşük çözünürlük).",
    secenekler: ["Suda az çözünür", "Çok çözünür", "Tamamen iyonlaşır", "Asit gibi davranır"],
    dogru: 0,
  },
  {
    kod: "KİM.11.2.14",
    zorluk: 3,
    soru: "PbI₂(s) ⇌ Pb²⁺ + 2I⁻ dengesine NaI eklenirse PbI₂ çözünürlüğü?",
    aciklama: "I⁻ ortak iyon → denge sola kayar → çözünürlük azalır (Le Chatelier).",
    secenekler: ["Azalır", "Artar", "Değişmez", "Sıfır olur"],
    dogru: 0,
  },
  {
    kod: "KİM.11.2.14",
    zorluk: 2,
    soru: "Çözünürlük dengesinde sıcaklık artışı endotermik çözünme için ne yapar?",
    aciklama: "Endotermik çözünmede ısı vermek dengeyi ürün yönüne kaydırır → çözünürlük artar.",
    secenekler: ["Çözünürlüğü artırır", "Her zaman azaltır", "Etkilemez", "Kçç sıfır olur"],
    dogru: 0,
  },
  {
    kod: "KİM.12.1.2",
    zorluk: 2,
    soru: "Aktiflik sıralamasında en tepede hangi metal bulunur?",
    aciklama: "Li, K, Ca, Na, Mg, Al, Zn, Fe... gibi sıralamada lityum en aktiftir (genel öğretim sıralaması).",
    secenekler: ["Lityum", "Altın", "Bakır", "Gümüş"],
    dogru: 0,
  },
];
