// Ek soru bankası B — 11.1, 11.2, 11.3, 12.1, 12.2, 12.3 temaları (her temada en az 15 soru hedefi)
// seed-questions.ts tarafından import edilir.
import type { SoruKayit } from "./questions-bank-extra";

export const EK_SORULAR1112: SoruKayit[] = [
  // ===== 11.1 Etkileşim (ek) =====
  {
    kod: "KİM.11.1.1",
    zorluk: 1,
    soru: "Ortamdan ısı alarak gerçekleşen tepkimelere ne ad verilir?",
    aciklama: "Ortamdan ısı alan tepkimeler endotermiktir (ΔH > 0); ortama ısı veren tepkimeler ekzotermiktir (ΔH < 0).",
    secenekler: ["Endotermik tepkime", "Ekzotermik tepkime", "Nötr tepkime", "Fotokimyasal tepkime"],
    dogru: 0,
  },
  {
    kod: "KİM.11.1.1",
    zorluk: 2,
    soru: "Ortama ısı vererek gerçekleşen bir tepkime için hangisi doğrudur?",
    aciklama: "Ekzotermik tepkimelerde ürünlerin enerjisi girenlerden düşüktür; açığa çıkan enerji ortama verilir (ΔH < 0).",
    secenekler: ["ΔH değeri negatiftir", "ΔH değeri pozitiftir", "Enerji korunmaz", "Tepkime ısı almadan olmaz"],
    dogru: 0,
  },
  {
    kod: "KİM.11.1.2",
    zorluk: 2,
    soru: "Aynı kütledeki yakıtlardan hangisi enerji kaynağı olarak en yüksek ısı değerine sahiptir?",
    aciklama: "Doğal gaz (metan) birim kütle başına yüksek ısı verir ve daha temiz yanar; kömür daha fazla karbon ve kirletici içerir.",
    secenekler: ["Doğal gaz (metan)", "Odun", "Kömür", "Tezek"],
    dogru: 0,
  },
  {
    kod: "KİM.11.1.3",
    zorluk: 3,
    soru: "Bağ enerjileri kullanılarak tepkime entalpisi nasıl hesaplanır?",
    aciklama: "ΔH = Kırılan bağların enerjisi - Oluşan bağların enerjisi. Bağ kırmak enerji ister (endotermik), bağ oluşumu enerji verir (ekzotermik).",
    secenekler: [
      "Kırılan bağlar - oluşan bağlar",
      "Oluşan bağlar - kırılan bağlar",
      "Sadece kırılan bağlar",
      "Sadece oluşan bağlar",
    ],
    dogru: 0,
  },
  {
    kod: "KİM.11.1.4",
    zorluk: 3,
    soru: "Bir bileşiğin elementlerinden oluşması sırasındaki 1 mol başına entalpi değişimine ne denir?",
    aciklama: "Standart molar oluşum entalpisi (ΔH°f): elementlerinden (en kararlı hâllerinde) 1 mol bileşik oluşurkenki entalpi değişimidir.",
    secenekler: [
      "Standart oluşum entalpisi",
      "Yanma entalpisi",
      "Nötralleşme entalpisi",
      "Çözünme entalpisi",
    ],
    dogru: 0,
  },
  {
    kod: "KİM.11.1.5",
    zorluk: 2,
    soru: "Taneciklerin tepkimeye girebilmesi için sahip olması gereken minimum enerjiye ne denir?",
    aciklama: "Aktifleşme (aktivasyon) enerjisi: tepkimenin başlayabilmesi için taneciklerin aşması gereken enerji engelidir.",
    secenekler: ["Aktifleşme enerjisi", "İyonlaşma enerjisi", "Bağ enerjisi", "Serbest enerji"],
    dogru: 0,
  },
  {
    kod: "KİM.11.1.7",
    zorluk: 2,
    soru: "Bir tepkimenin hızını artıran aşağıdaki faktörlerden hangisi değildir?",
    aciklama: "Sıcaklık artışı, derişim artışı, katalizör ve temas yüzeyinin artması hızı artırır. Katalizör Ea'yı düşürür; sıcaklığı düşürmek hızı azaltır.",
    secenekler: [
      "Ortam sıcaklığını düşürmek",
      "Katalizör eklemek",
      "Derişimi artırmak",
      "Temas yüzeyini artırmak",
    ],
    dogru: 0,
  },
  {
    kod: "KİM.11.1.6",
    zorluk: 3,
    soru: "Zamanla tepkime hızı genellikle neden azalır?",
    aciklama: "Tepkime ilerledikçe girenlerin derişimi azalır; tanecik çarpışma sayısı düştüğü için hız azalır.",
    secenekler: [
      "Girenlerin derişimi azaldığı için",
      "Ürünlerin derişimi azaldığı için",
      "Sıcaklık arttığı için",
      "Katalizör yok olduğu için",
    ],
    dogru: 0,
  },

  // ===== 11.2 Çeşitlilik (ek) =====
  {
    kod: "KİM.11.2.3",
    zorluk: 3,
    soru: "aA + bB ⇌ cC + dD tepkimesi için denge sabiti (Kc) ifadesi hangisidir?",
    aciklama: "Kc = [C]ᶜ·[D]ᵈ / [A]ᵃ·[B]ᵇ; ürünlerin derişimlerinin katsayıları kadar kuvveti, girenlerinkine bölünür.",
    secenekler: [
      "Kc = [C]ᶜ·[D]ᵈ / [A]ᵃ·[B]ᵇ",
      "Kc = [A]ᵃ·[B]ᵇ / [C]ᶜ·[D]ᵈ",
      "Kc = [A]+[B] / [C]+[D]",
      "Kc = [C]·[D] / [A]·[B]",
    ],
    dogru: 0,
  },
  {
    kod: "KİM.11.2.5",
    zorluk: 2,
    soru: "Dengedeki bir sisteme dışarıdan müdahale edildiğinde sistemin tepkisi ne olur?",
    aciklama: "Le Chatelier ilkesi: sistem, uygulanan değişikliğin etkisini azaltacak yönde kayar.",
    secenekler: [
      "Etkiyi azaltacak yönde kayar",
      "Hiç tepki vermez",
      "Etkiyi artıracak yönde kayar",
      "Her zaman ürünlere kayar",
    ],
    dogru: 0,
  },
  {
    kod: "KİM.11.2.7",
    zorluk: 3,
    soru: "Brønsted-Lowry asit-baz tanımına göre asit nedir?",
    aciklama: "Brønsted-Lowry: asit proton (H⁺) veren, baz proton alan maddedir. (Arrhenius'tan daha geneldir.)",
    secenekler: [
      "Proton (H⁺) veren madde",
      "Elektron çifti alan madde",
      "Suda OH⁻ oluşturan madde",
      "Sadece metal içeren madde",
    ],
    dogru: 0,
  },

  // ===== 11.3 Sürdürülebilirlik (ek) =====
  {
    kod: "KİM.11.3.1",
    zorluk: 1,
    soru: "Yeşil hidrojenin 'yeşil' olarak adlandırılmasının nedeni nedir?",
    aciklama: "Yeşil hidrojen, yenilenebilir enerji kaynakları kullanılarak üretilir ve üretimi sırasında karbon salımı yok denecek kadar azdır.",
    secenekler: [
      "Üretiminde karbon salımının çok az olması",
      "Renginin yeşil olması",
      "Sadece bitkilerden elde edilmesi",
      "Suyu yeşile boyaması",
    ],
    dogru: 0,
  },
  {
    kod: "KİM.11.3.1",
    zorluk: 2,
    soru: "Evsel atıklardan fermantasyonla hidrojen eldesinde atıkların rolü nedir?",
    aciklama: "Organik atıklar mikroorganizmalarca fermente edilir; bu süreçte biyogaz ve hidrojen gibi değerli ürünler açığa çıkar. Atık hem bertaraf edilir hem enerjiye dönüşür.",
    secenekler: [
      "Mikroorganizmalara besin olarak hidrojen üretimini sağlamak",
      "Sadece çöpü azaltmak",
      "Oksijen üretmek",
      "Plastik üretmek",
    ],
    dogru: 0,
  },
  {
    kod: "KİM.11.3.1",
    zorluk: 2,
    soru: "Hidrojenin yakıt olarak kullanılmasının çevresel avantajı nedir?",
    aciklama: "Hidrojen yandığında (yakıt pilinde) ana ürün su buharıdır; CO₂ gibi sera gazı üretmez.",
    secenekler: [
      "Yanma ürünü olarak su oluşturur, CO₂ üretmez",
      "CO₂ üretir ama az miktarda",
      "Sadece ısı üretir, enerji vermez",
      "Ozon tabakasını kalınlaştırır",
    ],
    dogru: 0,
  },
  {
    kod: "KİM.11.3.1",
    zorluk: 3,
    soru: "Fermantasyon sürecinin verimini artırmak için aşağıdakilerden hangisi en uygundur?",
    aciklama: "Mikroorganizmalar için uygun sıcaklık ve besin ortamı sağlamak fermantasyon verimini artırır; atığın ön işlemi de etkilidir.",
    secenekler: [
      "Mikroorganizmalara uygun sıcaklık ve besin sağlamak",
      "Atığa tuz eklemek",
      "Atığı dondurmak",
      "Atığı plastikle karıştırmak",
    ],
    dogru: 0,
  },
  {
    kod: "KİM.11.3.1",
    zorluk: 3,
    soru: "Evsel atıklardan yeşil hidrojen üretiminde aşağıdakilerden hangisi 'sürdürülebilir' bir yaklaşımdır?",
    aciklama: "Atığı enerji kaynağına dönüştürmek hem atık sorununu azaltır hem fosil yakıt ihtiyacını düşürür — döngüsel ekonomi yaklaşımıdır.",
    secenekler: [
      "Atığı enerji kaynağına dönüştürmek",
      "Atığı yakarak yok etmek",
      "Atığı denize dökmek",
      "Atık üretimini artırmak",
    ],
    dogru: 0,
  },
  {
    kod: "KİM.11.3.2",
    zorluk: 2,
    soru: "Nanoteknolojik bir ürün satın alırken bilinçli bir tüketici ne yapmalıdır?",
    aciklama: "Ürünün fayda ve risklerini (içerik, etiket, çevresel etki) birlikte değerlendirmek eleştirel yaklaşımdır.",
    secenekler: [
      "Fayda ve risklerini birlikte değerlendirmek",
      "Sadece reklamlara güvenmek",
      "En ucuzunu almak",
      "İçeriğine hiç bakmamak",
    ],
    dogru: 0,
  },
  {
    kod: "KİM.11.3.2",
    zorluk: 2,
    soru: "Güneş kremindeki nanoparçacıklar hakkında doğru yaklaşım hangisidir?",
    aciklama: "Nanoparçacıklar (örn. ZnO, TiO₂) UV koruması sağlar ancak olası çevresel etkileri (ör. sucul canlılar) araştırılmalı; dengeli ve bilgili seçim yapılmalıdır.",
    secenekler: [
      "Faydasını ve olası risklerini araştırarak seçim yapmak",
      "Tüm nanoparçacıkları kesinlikle zararlı saymak",
      "Nanoparçacıkların her zaman zararsız olduğunu varsaymak",
      "Etikete hiç bakmamak",
    ],
    dogru: 0,
  },
  {
    kod: "KİM.11.3.2",
    zorluk: 3,
    soru: "Nanomalzeme içeren bir ürünün 'güvenli' sayılması için hangisi gereklidir?",
    aciklama: "Ürünlerin güvenliği bilimsel risk değerlendirmesi ve yetkili kurum düzenlemeleriyle belirlenir; reklam veya görünümle değil.",
    secenekler: [
      "Bilimsel risk değerlendirmesi ve düzenlemelerle belgelenmesi",
      "Pahalı olması",
      "Reklamlarda övülmesi",
      "Ambalajının parlak olması",
    ],
    dogru: 0,
  },
  {
    kod: "KİM.11.3.3",
    zorluk: 1,
    soru: "Mikroplastik nedir?",
    aciklama: "Mikroplastikler, 5 mm'den küçük plastik parçacıklarıdır; büyük plastiklerin parçalanması veya doğrudan üretim (örn. kozmetikteki mikroboncuklar) ile oluşur.",
    secenekler: [
      "5 mm'den küçük plastik parçacıkları",
      "Biyolojik olarak üretilen polimerler",
      "Metal nanoparçacıklar",
      "Doğal kauçuk",
    ],
    dogru: 0,
  },
  {
    kod: "KİM.11.3.3",
    zorluk: 2,
    soru: "Mikroplastiklerin ekosisteme temel zararı nedir?",
    aciklama: "Deniz canlıları mikroplastikleri besin sanarak yer; mikroplastikler besin zincirine girerek canlılarda birikebilir ve toksik maddeleri taşıyabilir.",
    secenekler: [
      "Besin zincirine girip canlılarda birikmesi",
      "Oksijen üretmesi",
      "Toprağı gübrelemesi",
      "Suyun pH'ını yükseltmesi",
    ],
    dogru: 0,
  },
  {
    kod: "KİM.11.3.3",
    zorluk: 2,
    soru: "Mikroplastik kirliliğini azaltmak için bireysel olarak en etkili davranış hangisidir?",
    aciklama: "Tek kullanımlık plastik tüketimini azaltmak ve plastikleri geri dönüşüme göndermek mikroplastik oluşumunu azaltır.",
    secenekler: [
      "Tek kullanımlık plastik kullanımını azaltmak",
      "Plastikleri doğaya atmak",
      "Plastikleri yakmak",
      "Mikroboncuklu kozmetik kullanmak",
    ],
    dogru: 0,
  },
  {
    kod: "KİM.11.3.3",
    zorluk: 3,
    soru: "Kozmetik ürünlerdeki mikroboncukların yasaklanmasının nedeni nedir?",
    aciklama: "Mikroboncuklar arıtma sistemlerinden geçerek denizlere ulaşan doğrudan mikroplastik kaynağıdır; bu yüzden birçok ülkede yasaklanmıştır.",
    secenekler: [
      "Arıtmayla tutulamayıp denizlere ulaşan mikroplastik kaynağı olması",
      "Ciltte renk değişimi yapması",
      "Kozmetiği pahalandırması",
      "Kokusuz olması",
    ],
    dogru: 0,
  },
  {
    kod: "KİM.11.3.3",
    zorluk: 3,
    soru: "Biyobozunur (doğada çözünen) plastiklerin mikroplastik sorununu çözmede sınırı nedir?",
    aciklama: "Biyobozunur plastikler belirli koşullarda (sıcaklık, mikroorganizma) parçalanır; deniz gibi ortamlarda da mikroplastik oluşturabilir ve yine de doğru atık yönetimi gerekir.",
    secenekler: [
      "Her ortamda hızla parçalanmaz, atık yönetimi yine gerekir",
      "Tamamen zararsızdır, hiçbir atık bırakmaz",
      "Sadece denizde parçalanır",
      "Hepsini çözünebilir yapmak yasaktır",
    ],
    dogru: 0,
  },

  // ===== 12.1 Etkileşim (ek) =====
  {
    kod: "KİM.12.1.1",
    zorluk: 1,
    soru: "Bir tanecik elektron verdiğinde gerçekleşen olay aşağıdakilerden hangisidir?",
    aciklama: "Elektron verme yükseltgenmedir (oksidasyon); elektron alma indirgenmedir (redüksiyon). İkisi birlikte redoks tepkimesini oluşturur.",
    secenekler: ["Yükseltgenme", "İndirgenme", "Nötralleşme", "Çökelme"],
    dogru: 0,
  },
  {
    kod: "KİM.12.1.1",
    zorluk: 2,
    soru: "Redoks tepkimesinde elektron alan madde için hangisi doğrudur?",
    aciklama: "Elektron alan madde indirgenir ve başka maddeyi yükselttiği için 'indirgen ajan' olur.",
    secenekler: [
      "İndirgenir ve indirgen ajandır",
      "Yükseltgenir ve yükseltgen ajandır",
      "Sadece indirgenir, ajan olmaz",
      "Elektron kaybeder",
    ],
    dogru: 0,
  },
  {
    kod: "KİM.12.1.2",
    zorluk: 3,
    soru: "Zn, CuSO₄ çözeltisine atıldığında Zn çözünür ve bakır açığa çıkar. Bu durumda hangisi söylenebilir?",
    aciklama: "Çinko, bakırdan daha aktiftir; aktif metal, tuz çözeltisindeki daha az aktif metali yerinden çıkarır (yer değiştirme).",
    secenekler: [
      "Çinko, bakırdan daha aktiftir",
      "Bakır, çinkodan daha aktiftir",
      "İkisi de aynı aktifliktedir",
      "Tepkime gerçekleşmez",
    ],
    dogru: 0,
  },
  {
    kod: "KİM.12.1.3",
    zorluk: 2,
    soru: "Galvanik hücrede yükseltgenmenin gerçekleştiği elektrota ne denir?",
    aciklama: "Anotta yükseltgenme, katotta indirgenme olur. Elektronlar anottan katoda dış devre üzerinden akar.",
    secenekler: ["Anot", "Katot", "Tuz köprüsü", "Diyafram"],
    dogru: 0,
  },
  {
    kod: "KİM.12.1.4",
    zorluk: 3,
    soru: "Standart hücre potansiyeli (E°hücre) nasıl hesaplanır?",
    aciklama: "E°hücre = E°katot - E°anot. Pozitif değer tepkimenin kendiliğinden (spontan) olduğunu gösterir.",
    secenekler: [
      "E°katot - E°anot",
      "E°anot - E°katot",
      "E°katot + E°anot",
      "E°anot × E°katot",
    ],
    dogru: 0,
  },
  {
    kod: "KİM.12.1.6",
    zorluk: 2,
    soru: "Elektroliz olayı için aşağıdakilerden hangisi zorunludur?",
    aciklama: "Elektroliz, kendiliğinden gerçekleşmeyen tepkimeleri dış elektrik kaynağı (akım) ile gerçekleştirir; elektrolitik hücrede çalışır.",
    secenekler: [
      "Dış elektrik kaynağı (akım)",
      "Sadece ısı kaynağı",
      "Katalizör",
      "Tuz köprüsü",
    ],
    dogru: 0,
  },
  {
    kod: "KİM.12.1.7",
    zorluk: 3,
    soru: "Elektrolizde açığa çıkan madde miktarı neye bağlıdır?",
    aciklama: "Faraday yasalarına göre açığa çıkan madde miktarı, devreden geçen yük miktarıyla (akım × süre) doğru orantılıdır.",
    secenekler: [
      "Akım şiddeti ve süreye (yük miktarına)",
      "Sadece sıcaklığa",
      "Sadece çözelti rengine",
      "Hücrenin boyutuna",
    ],
    dogru: 0,
  },
  {
    kod: "KİM.12.1.8",
    zorluk: 2,
    soru: "Elektrolizle bir metali başka bir metalle kaplamak için kaplanacak cisim hangi elektrota bağlanır?",
    aciklama: "Kaplanacak cisim katoda bağlanır; çözeltideki metal iyonları katotta indirgenerek cismin üzerine ince tabaka hâlinde çöker (örn. gümüş kaplama).",
    secenekler: ["Katoda", "Anoda", "Tuz köprüsüne", "Her ikisine de"],
    dogru: 0,
  },
  {
    kod: "KİM.12.1.9",
    zorluk: 2,
    soru: "Demiri korozyondan korumanın en yaygın yollarından biri aşağıdakilerden hangisidir?",
    aciklama: "Galvanizleme (çinko kaplama), boyama ve katodik koruma korozyonu önler. Çinko, demirden aktif olduğu için demiri korur.",
    secenekler: [
      "Çinko ile kaplamak (galvanizleme)",
      "Tuzlu suda bekletmek",
      "Nemli ortamda saklamak",
      "Yüzeyini çizmek",
    ],
    dogru: 0,
  },

  // ===== 12.2 Çeşitlilik (ek) =====
  {
    kod: "KİM.12.2.1",
    zorluk: 2,
    soru: "Karbon atomları arasındaki çift bağ (C=C) kaç sigma ve kaç pi bağı içerir?",
    aciklama: "Çift bağ = 1 sigma + 1 pi bağıdır. Tek bağ yalnız sigma, üçlü bağ ise 1 sigma + 2 pi içerir.",
    secenekler: ["1 sigma + 1 pi", "2 sigma", "1 sigma + 2 pi", "2 pi"],
    dogru: 0,
  },
  {
    kod: "KİM.12.2.2",
    zorluk: 3,
    soru: "Metan (CH₄) molekülündeki karbon atomunun hibritleşme türü nedir?",
    aciklama: "Metanda karbon dört bağ yapar ve sp³ hibritleşmesi gösterir; geometrisi tetrahedraldir.",
    secenekler: ["sp³", "sp²", "sp", "hibritleşme yoktur"],
    dogru: 0,
  },
  {
    kod: "KİM.12.2.3",
    zorluk: 3,
    soru: "Metan (CH₄) molekülünün geometrisi ve bağ açısı nedir?",
    aciklama: "CH₄ tetrahedral geometrilidir; bağ açısı yaklaşık 109,5°dir.",
    secenekler: ["Tetrahedral, 109,5°", "Düzlem üçgen, 120°", "Doğrusal, 180°", "Açısal, 104,5°"],
    dogru: 0,
  },
  {
    kod: "KİM.12.2.4",
    zorluk: 2,
    soru: "C₂H₆ formülü hangi tür gösterimdir?",
    aciklama: "C₂H₆, atomların türünü ve sayısını gösteren kapalı (molekül) formüldür. Açık formül CH₃CH₃ şeklindedir.",
    secenekler: ["Kapalı (molekül) formül", "Açık formül", "Yarı açık formül", "Top ve çubuk modeli"],
    dogru: 0,
  },
  {
    kod: "KİM.12.2.5",
    zorluk: 1,
    soru: "Yalnızca tekli karbon-karbon bağı içeren doymuş hidrokarbonlara ne denir?",
    aciklama: "Alkanlar yalnız tek bağ içerir (genel formül CₙH₂ₙ₊₂); alkenler çift bağ, alkinler üçlü bağ içerir.",
    secenekler: ["Alkan", "Alken", "Alkin", "Aromatik hidrokarbon"],
    dogru: 0,
  },
  {
    kod: "KİM.12.2.6",
    zorluk: 3,
    soru: "Beş karbonlu düz zincirli alkanın adı ve formülü hangisidir?",
    aciklama: "C₅H₁₂ pentandır (düz zincirli alkan: n-pentan). Alkan adlandırmasında kök + -an eki kullanılır.",
    secenekler: ["Pentan (C₅H₁₂)", "Bütan (C₄H₁₀)", "Heksan (C₆H₁₄)", "Propan (C₃H₈)"],
    dogru: 0,
  },
  {
    kod: "KİM.12.2.7",
    zorluk: 3,
    soru: "C₄H₁₀ kapalı formülüne sahip kaç farklı yapısal izomer yazılabilir?",
    aciklama: "C₄H₁₀ için 2 yapısal izomer vardır: n-bütan (düz zincir) ve izobütan (dallanmış).",
    secenekler: ["2", "1", "3", "4"],
    dogru: 0,
  },
  {
    kod: "KİM.12.2.8",
    zorluk: 2,
    soru: "Aynı tür alkanlarda karbon sayısı arttıkça kaynama noktası nasıl değişir?",
    aciklama: "Zincir uzadıkça moleküller arası London kuvvetleri artar, bu yüzden kaynama noktası yükselir.",
    secenekler: ["Yükselir", "Düşer", "Değişmez", "Düzensiz değişir"],
    dogru: 0,
  },
  {
    kod: "KİM.12.2.9",
    zorluk: 2,
    soru: "-OH grubu içeren organik bileşikler hangi fonksiyonel gruba aittir?",
    aciklama: "-OH (hidroksil) grubu alkolleri belirler (örn. etanol C₂H₅OH). -COOH karboksilik asit, -CHO aldehit grubudur.",
    secenekler: ["Alkol", "Karboksilik asit", "Aldehit", "Eter"],
    dogru: 0,
  },
  {
    kod: "KİM.12.2.12",
    zorluk: 2,
    soru: "Karbon temelli yakıtların (kömür, petrol, doğal gaz) tam yanmasının başlıca ürünü nedir?",
    aciklama: "Karbon içeren yakıtların tam yanması CO₂ ve su üretir; CO₂ sera gazı olarak iklim değişikliğine katkı yapar.",
    secenekler: ["CO₂ ve su", "Sadece CO", "SO₂ ve NO", "Kurum ve kül"],
    dogru: 0,
  },

  // ===== 12.3 Sürdürülebilirlik (ek) =====
  {
    kod: "KİM.12.3.1",
    zorluk: 2,
    soru: "Boyaya duyarlı güneş pillerinin (DSSC) çalışma prensibinde 'boya' molekülünün görevi nedir?",
    aciklama: "Boya molekülü görünür ışığı soğurur ve elektronları yarı iletkene (TiO₂) aktarır; böylece ışık elektriğe dönüşür.",
    secenekler: [
      "Işığı soğurup elektron aktarmak",
      "Hücreyi renklendirip süslemek",
      "Elektronları durdurmak",
      "Isı üretmek",
    ],
    dogru: 0,
  },
  {
    kod: "KİM.12.3.1",
    zorluk: 3,
    soru: "Boyaya duyarlı güneş pillerinin verimini artırmak için aşağıdakilerden hangisi araştırılır?",
    aciklama: "Daha geniş ışık aralığını soğuran ve daha kararlı boya molekülleri ile yüzey alanı yüksek nanoyapılı elektrotlar verimi artırır.",
    secenekler: [
      "Geniş spektrumlu, kararlı boya ve nanoyapılı elektrotlar",
      "Daha kalın cam kullanmak",
      "Boyayı koyulaştırmak",
      "Hücreyi karartmak",
    ],
    dogru: 0,
  },
  {
    kod: "KİM.12.3.1",
    zorluk: 2,
    soru: "Boyaya duyarlı güneş pillerinin silisyum pillerine göre avantajı nedir?",
    aciklama: "DSSC'ler düşük maliyetli malzemelerle, esnek yüzeylerde ve düşük ışıkta da çalışabilir; üretimi daha az enerji ister.",
    secenekler: [
      "Düşük maliyetli ve düşük ışıkta çalışabilmesi",
      "Her zaman daha verimli olması",
      "Atık üretmemesi",
      "Güneş gerektirmemesi",
    ],
    dogru: 0,
  },
  {
    kod: "KİM.12.3.1",
    zorluk: 3,
    soru: "Güneş pili teknolojilerinde 'sürdürülebilirlik' denildiğinde öncelikli ölçüt nedir?",
    aciklama: "Üretimde az enerji/toksik madde kullanımı, uzun ömür ve geri dönüştürülebilirlik sürdürülebilirliği belirler.",
    secenekler: [
      "Üretim maliyeti, toksisite ve geri dönüşüm dengesi",
      "Sadece görünüm",
      "Sadece pilin ağırlığı",
      "Sadece reklamı",
    ],
    dogru: 0,
  },
  {
    kod: "KİM.12.3.2",
    zorluk: 1,
    soru: "Biyobozunur polimer ne demektir?",
    aciklama: "Biyobozunur polimerler, mikroorganizmaların etkisiyle doğada CO₂, su ve biyokütleye dönüşebilen plastiklerdir (örn. PLA, nişasta bazlı).",
    secenekler: [
      "Mikroorganizmalarca doğada parçalanabilen polimer",
      "Asla parçalanmayan polimer",
      "Petrolden elde edilen her polimer",
      "Metal içeren polimer",
    ],
    dogru: 0,
  },
  {
    kod: "KİM.12.3.2",
    zorluk: 2,
    soru: "Biyobozunur polimer üretiminde tercih edilen yenilenebilir kaynak aşağıdakilerden hangisidir?",
    aciklama: "Mısır nişastası, şeker kamışı gibi bitkisel kaynaklardan PLA (polilaktik asit) üretilir; bu kaynaklar yenilenebilirdir.",
    secenekler: [
      "Mısır nişastası gibi bitkisel kaynaklar",
      "Ham petrol",
      "Kömür",
      "Doğal gaz",
    ],
    dogru: 0,
  },
  {
    kod: "KİM.12.3.2",
    zorluk: 2,
    soru: "Biyobozunur bir ambalaj seçerken dikkat edilmesi gereken en önemli nokta nedir?",
    aciklama: "Ürünün hangi koşullarda bozunduğu (endüstriyel kompost vs doğa) ve sertifikası önemlidir; yanlış atık akışına girerse çözünmeyebilir.",
    secenekler: [
      "Hangi koşullarda bozunduğu ve sertifikası",
      "Sadece rengi",
      "Sadece fiyatı",
      "Sadece markası",
    ],
    dogru: 0,
  },
  {
    kod: "KİM.12.3.2",
    zorluk: 3,
    soru: "PLA (polilaktik asit) gibi biyoplastiklerin geleneksel plastiklere göre dezavantajı ne olabilir?",
    aciklama: "PLA yalnızca belirli (endüstriyel kompost) koşullarda hızla bozunur; normal çöpte veya denizde uzun süre kalabilir ve geri dönüşüm akışını kirletebilir.",
    secenekler: [
      "Belirli koşullar olmadan yavaş bozunması",
      "Her zaman daha pahalı üretilmesi",
      "Tamamen yenilenemez olması",
      "Her koşulda petrol plastiğinden kötü olması",
    ],
    dogru: 0,
  },
  {
    kod: "KİM.12.3.3",
    zorluk: 2,
    soru: "Yapay zekâ uygulamaları sürdürülebilirliğe hangi yolla katkı sağlayabilir?",
    aciklama: "Yapay zekâ enerji tüketimini optimize edebilir, üretim süreçlerinde atığı azaltabilir ve kaynak kullanımını verimli hâle getirebilir.",
    secenekler: [
      "Enerji ve kaynak kullanımını optimize ederek",
      "Her zaman daha çok enerji harcayarak",
      "Atığı artırarak",
      "İnsan işini tamamen durdurarak",
    ],
    dogru: 0,
  },
  {
    kod: "KİM.12.3.3",
    zorluk: 3,
    soru: "Yapay zekânın çevresel maliyeti nedir?",
    aciklama: "Büyük yapay zekâ modellerinin eğitimi çok yüksek elektrik tüketir; bu da fosil yakıt kullanılıyorsa karbon ayak izini artırır.",
    secenekler: [
      "Model eğitiminin yüksek enerji tüketimi",
      "Hiçbir maliyeti yoktur",
      "Sadece su kirliliği yaratır",
      "Yalnızca plastik atık üretir",
    ],
    dogru: 0,
  },
  {
    kod: "KİM.12.3.3",
    zorluk: 3,
    soru: "'Yeşil kimya'da yapay zekâdan nasıl yararlanılabilir?",
    aciklama: "Yapay zekâ, daha az toksik ve daha az atık üreten yeni sentez yollarını ve katalizörleri hızla tarayıp önerebilir.",
    secenekler: [
      "Daha yeşil sentez yollarını ve katalizörleri keşfetmek için",
      "Kimyasalları daha toksik hâle getirmek için",
      "Deney yapmayı tamamen yasaklamak için",
      "Yalnızca reklam amaçlı",
    ],
    dogru: 0,
  },
  {
    kod: "KİM.12.3.3",
    zorluk: 2,
    soru: "Bir yapay zekâ uygulamasının 'sürdürülebilir' sayılması için hangi ölçüt önemlidir?",
    aciklama: "Uygulamanın sağladığı tasarrufun, eğitim/çalışma enerjisi maliyetinden büyük olması ve veri/etki etiğine uyması gerekir.",
    secenekler: [
      "Sağladığı net çevresel fayda ile enerji maliyeti dengesi",
      "Sadece popülerliği",
      "Sadece hızı",
      "Sadece maliyeti",
    ],
    dogru: 0,
  },
  {
    kod: "KİM.12.3.3",
    zorluk: 2,
    soru: "Akıllı şebekelerde yapay zekâ hangi sürdürülebilirlik hedefine hizmet eder?",
    aciklama: "Akıllı şebekeler, üretim-tüketim dengesini gerçek zamanlı optimize ederek enerji verimliliğini ve yenilenebilir kaynak kullanımını artırır.",
    secenekler: [
      "Enerji verimliliğini artırmak",
      "Enerji israfını artırmak",
      "Kömür kullanımını teşvik etmek",
      "Elektriği tamamen kaldırmak",
    ],
    dogru: 0,
  },
];
