// Tamamlayıcı soru bankası (9-10. sınıf): her ünitede en az 15 soru hedefi için ek sorular.
// seed-questions.ts tarafından import edilir (idempotent: prompt eşleşmesiyle tekrar eklenmez).

import type { SoruKayit } from "./questions-bank-extra";

export const EK_SORULAR_DOLDUR_9_10: SoruKayit[] = [
  // ===== U1 Kimya Hayattır (KİM.9.1.1 +3, 9.1.2 +2, 9.1.7 +3) =====
  {
    kod: "KİM.9.1.1",
    zorluk: 1,
    soru: "Aşağıdakilerden hangisi kimya biliminin günlük hayata katkılarından biri DEĞİLDİR?",
    aciklama: "Deprem dalgalarının incelenmesi fizik (jeofizik) alanıdır. Gıda koruyucuları, ambalaj malzemeleri ve ilaç sentezi kimyanın günlük hayata katkılarıdır.",
    secenekler: [
      "Deprem dalgalarının yayılma hızının hesaplanması",
      "Gıdaların bozulmasını geciktiren koruyucuların geliştirilmesi",
      "Daha dayanıklı ve hafif ambalaj malzemelerinin üretilmesi",
      "Hastalar için yeni ilaç moleküllerinin sentezlenmesi",
    ],
    dogru: 0,
  },
  {
    kod: "KİM.9.1.1",
    zorluk: 2,
    soru: "Hastanelerde kullanılan dezenfektanların ve serum içindeki minerallerin üretiminde görev alan bilim insanı öncelikle hangi alanda uzmandır?",
    aciklama: "Dezenfektanlar kimyasal maddelerdir; serumdaki mineral tuzları da kimyasal bileşiklerdir. Bu ürünlerin geliştirilmesi kimya biliminin katkısıdır.",
    secenekler: ["Kimya", "Astronomi", "Botanik", "Zooloji"],
    dogru: 0,
  },
  {
    kod: "KİM.9.1.1",
    zorluk: 1,
    soru: "Bir öğrenci; tuz, şeker, su ve alüminyum folyoyu kimya açısından inceliyor. Öğrencinin ilgi alanına giren inceleme hangisidir?",
    aciklama: "Kimya; maddelerin yapısını, özelliklerini ve birbirleriyle etkileşimlerini inceler. Fiyat ve marka karşılaştırması kimyanın konusu değildir.",
    secenekler: [
      "Bu maddelerin yapılarının ve birbirleriyle etkileşimlerinin incelenmesi",
      "Bu maddelerin fiyatlarının karşılaştırılması",
      "Bu maddelerin markalarının karşılaştırılması",
      "Bu maddelerin hangi mağazada satıldığının belirlenmesi",
    ],
    dogru: 0,
  },
  {
    kod: "KİM.9.1.2",
    zorluk: 2,
    soru: "Kireç çözücü (asit içeren) ürün ile klor bazlı çamaşır suyu karıştırılırsa hangi tehlike oluşabilir?",
    aciklama: "Asit ile çamaşır suyu (hipoklorit) karıştırıldığında zehirli klor gazı açığa çıkabilir. Temizlik ürünleri asla birbiriyle karıştırılmamalıdır.",
    secenekler: [
      "Zehirli klor gazı açığa çıkabilir",
      "Karışım daha etkili temizler",
      "Karışımın rengi değişir ama zararsızdır",
      "Sadece köpürme olur, tehlikesi yoktur",
    ],
    dogru: 0,
  },
  {
    kod: "KİM.9.1.2",
    zorluk: 1,
    soru: "Etiketinde alev (yanıcı) piktogramı bulunan bir kimyasal ürün nasıl saklanmalıdır?",
    aciklama: "Alev piktogramı yanıcı madde demektir. Bu ürünler ateş, kıvılcım ve ısı kaynaklarından uzak, serin yerde saklanmalıdır.",
    secenekler: [
      "Ateş ve kıvılcım kaynaklarından uzak, serin bir yerde",
      "Buzdolabının içinde",
      "Güneş alan bir cam önünde",
      "Elektrikli ısıtıcının hemen yanında",
    ],
    dogru: 0,
  },
  {
    kod: "KİM.9.1.7",
    zorluk: 1,
    soru: "Mg atomu (12 elektron) kararlı hâle geçmek için 2 elektron verirse oluşan tanecik için hangisi doğrudur?",
    aciklama: "Elektron veren atom pozitif yüklü katyon olur: Mg → Mg²⁺ + 2e⁻. Mg²⁺ iyonunda 10 elektron kalır (neon elektron düzeni).",
    secenekler: [
      "Mg²⁺ katyonu oluşur",
      "Mg²⁻ anyonu oluşur",
      "Nötr Mg atomu olarak kalır",
      "Anyon oluşur ve elektron sayısı 12 olur",
    ],
    dogru: 0,
  },
  {
    kod: "KİM.9.1.7",
    zorluk: 2,
    soru: "Oksijen atomu (8O) kararlı hâle geçmek için 2 elektron alırsa hangi iyon oluşur?",
    aciklama: "Elektron alan atom negatif yüklü anyon olur: O + 2e⁻ → O²⁻ (oksit iyonu). O²⁻ iyonu neon elektron düzenine ulaşır.",
    secenekler: ["O²⁻ (oksit) iyonu", "O²⁺ iyonu", "O⁻ iyonu", "Hiç iyon oluşmaz"],
    dogru: 0,
  },
  {
    kod: "KİM.9.1.7",
    zorluk: 3,
    soru: "Na⁺, Mg²⁺ ve Al³⁺ iyonlarının her birinde kaç elektron bulunur?",
    aciklama: "Na (11e) 1 elektron, Mg (12e) 2 elektron, Al (13e) 3 elektron verince üçü de 10 elektronlu neon düzenine ulaşır. Bu tür iyonlara izoelektronik denir.",
    secenekler: [
      "Üçü de 10 elektron içerir",
      "Sırasıyla 10, 12 ve 13 elektron içerir",
      "Sırasıyla 11, 12 ve 13 elektron içerir",
      "Üçü de 8 elektron içerir",
    ],
    dogru: 0,
  },
  // ===== U2 Atomdan Periyodik Tabloya (KİM.9.1.3 +1, 9.1.4 +1, 9.1.5 +1, 9.1.6 +1) =====
  {
    kod: "KİM.9.1.3",
    zorluk: 2,
    soru: "Rutherford'un altın folyo deneyinde bazı ışınların büyük açıyla saçılması hangi sonuca ulaşılmasını sağlamıştır?",
    aciklama: "Saçılan ışınlar, atomdaki pozitif yük ve kütlenin çok küçük bir hacimde (çekirdekte) toplandığını gösterdi. Böylece Thomson modeli değişerek bilimsel bilginin gelişebileceği görüldü.",
    secenekler: [
      "Pozitif yük ve kütle atomun merkezinde çok küçük bir hacimde toplanmıştır",
      "Atomun kütlesi hacmine homojen dağılmıştır",
      "Elektronlar belirli yörüngelerde döner",
      "Atom parçalanamaz içi dolu bir küredir",
    ],
    dogru: 0,
  },
  {
    kod: "KİM.9.1.4",
    zorluk: 3,
    soru: "Aşağıdaki orbitallerden hangisinin enerjisi en yüksektir?",
    aciklama: "Orbitallerin bağıl enerjisi: 3s < 3p < 4s < 3d biçimindedir (Aufbau ilkesi). 4s, 3d'den önce dolar.",
    secenekler: ["3d", "4s", "3p", "3s"],
    dogru: 0,
  },
  {
    kod: "KİM.9.1.5",
    zorluk: 3,
    soru: "Fosfor (15P) elementinin temel hâl elektron dizilimi hangisidir?",
    aciklama: "Fosfor 15 elektrona sahiptir. Dizilim: 1s² 2s² 2p⁶ 3s² 3p³ olur (Hund kuralına göre 3p'ye 3 elektron birer birer yerleşir).",
    secenekler: [
      "1s² 2s² 2p⁶ 3s² 3p³",
      "1s² 2s² 2p⁶ 3s² 3p⁵",
      "1s² 2s² 2p⁶ 3s² 3d³",
      "1s² 2s² 2p⁶ 3s¹ 3p⁴",
    ],
    dogru: 0,
  },
  {
    kod: "KİM.9.1.6",
    zorluk: 2,
    soru: "Elektron dizilimi 1s² 2s² 2p⁶ 3s² 3p⁶ 4s¹ olan element için hangisi doğrudur?",
    aciklama: "4 enerji düzeyi (katman) kullanıldığı için element 4. periyottadır; son katmanda 1 elektron olduğu için 1A grubundadır. Bu element potasyumdur (K).",
    secenekler: [
      "4. periyot 1A grubundadır",
      "3. periyot 1A grubundadır",
      "4. periyot 2A grubundadır",
      "3. periyot 8A grubundadır",
    ],
    dogru: 0,
  },
  // ===== U3 Etkileşimler (KİM.9.2.1 +1, 9.2.2 +1, 9.2.3 +1, 9.2.4 +1, 9.2.5 +2, 9.2.6 +2) =====
  {
    kod: "KİM.9.2.1",
    zorluk: 1,
    soru: "Metalik bağın oluşumundaki temel etken aşağıdakilerden hangisidir?",
    aciklama: "Metal atomları valans elektronlarını ortaklaşa kullanır; oluşan serbest elektron denizi ile metal katyonları arasındaki elektrostatik çekim metalik bağı oluşturur.",
    secenekler: [
      "Metal katyonları ile serbest elektron denizi arasındaki elektrostatik çekim",
      "İki farklı metal atomunun elektron alışverişi",
      "Metal ile ametal arasındaki elektron paylaşımı",
      "Metal atomlarının birbirini itmesi",
    ],
    dogru: 0,
  },
  {
    kod: "KİM.9.2.2",
    zorluk: 2,
    soru: "Aşağıdaki bileşiklerden hangisi iyonik bağ içerir?",
    aciklama: "CaO'da metal (Ca) ile ametal (O) arasında elektron transferiyle iyonik bağ oluşur. CO₂, H₂O ve NH₃ ametaller arası kovalent bağlıdır.",
    secenekler: ["CaO", "CO₂", "H₂O", "NH₃"],
    dogru: 0,
  },
  {
    kod: "KİM.9.2.3",
    zorluk: 2,
    soru: "Aşağıdaki bileşiklerden hangisinde kovalent bağ bulunmaz?",
    aciklama: "KF'de potasyum (metal) elektronunu florine (ametal) verir; K⁺ ile F⁻ arasında iyonik bağ kurulur. CH₄, H₂ ve NH₃ kovalent bağlıdır.",
    secenekler: ["KF", "CH₄", "H₂", "NH₃"],
    dogru: 0,
  },
  {
    kod: "KİM.9.2.4",
    zorluk: 3,
    soru: "N₂ molekülünün Lewis yapısında azot atomları arasında kaç elektron çifti ortaklaşılır?",
    aciklama: "Azotun 5 değerlik elektronu vardır; oktetini tamamlamak için 3 elektronunu paylaşır. N₂'de azotlar arasında üçlü bağ (N≡N) bulunur, yani 3 elektron çifti ortaktır.",
    secenekler: ["3", "1", "2", "4"],
    dogru: 0,
  },
  {
    kod: "KİM.9.2.5",
    zorluk: 2,
    soru: "Aşağıdaki moleküllerden hangisi apolar moleküldür?",
    aciklama: "CCl₄'te C-Cl bağları polardır ancak molekül simetrik olduğundan dipoller birbirini sıfırlar ve molekül apolar olur. H₂O, NH₃ ve HCl polar moleküllerdir.",
    secenekler: ["CCl₄", "H₂O", "NH₃", "HCl"],
    dogru: 0,
  },
  {
    kod: "KİM.9.2.5",
    zorluk: 3,
    soru: "Bir molekülün polar olabilmesi için hangi iki koşul birlikte sağlanmalıdır?",
    aciklama: "Molekül polar bağlar içermeli ve bağ dipollerini sıfırlamayacak simetrik olmayan bir geometriye sahip olmalıdır. Simetrik moleküllerde (CO₂, CCl₄) dipoller birbirini götürür.",
    secenekler: [
      "Polar bağ içermeli ve molekül geometrisi simetrik olmamalı",
      "Yalnızca apolar bağ içermeli",
      "Tüm bağlar aynı iki atom arasında olmalı",
      "Molekül tam simetrik olmalı",
    ],
    dogru: 0,
  },
  {
    kod: "KİM.9.2.6",
    zorluk: 2,
    soru: "Fe₂O₃ bileşiğinin adı aşağıdakilerden hangisidir?",
    aciklama: "Oksijenin yükseltgenme basamağı -2 olduğundan 3 O için toplam -6 olur; nötrlük için 2 Fe toplam +6 olmalıdır, yani Fe +3'tür. Adı demir(III) oksittir.",
    secenekler: [
      "Demir(III) oksit",
      "Demir(II) oksit",
      "Demir oksür",
      "Demir(III) peroksit",
    ],
    dogru: 0,
  },
  {
    kod: "KİM.9.2.6",
    zorluk: 2,
    soru: "CuO bileşiğinin adı aşağıdakilerden hangisidir?",
    aciklama: "Oksijen -2 olduğu için bakır +2 yüklüdür (Cu²⁺). Bakırın +1 ve +2 yüklü iyonları olduğundan adlandırmada yükseltgenme basamağı belirtilir: bakır(II) oksit.",
    secenekler: [
      "Bakır(II) oksit",
      "Bakır(I) oksit",
      "Bakır oksür",
      "Bakır dioksit",
    ],
    dogru: 0,
  },
  // ===== U4 Etkileşimden Maddeye (KİM.9.2.7 +1, 9.2.8 +1, 9.2.9 +1, 9.2.10 +1, 9.2.11 +1, 9.2.12 +1, 9.2.13 +1) =====
  {
    kod: "KİM.9.2.7",
    zorluk: 2,
    soru: "Aşağıdaki saf maddelerden hangisinin molekülleri arasında hidrojen bağı etkileşimi görülür?",
    aciklama: "Hidrojen bağı; hidrojenin F, O veya N gibi elektronegatifliği yüksek atomlara bağlı olduğu moleküller arasında oluşur. HF bu koşulu sağlar; CH₄, H₂S ve HCl'de hidrojen bağı yoktur.",
    secenekler: ["HF", "CH₄", "H₂S", "HCl"],
    dogru: 0,
  },
  {
    kod: "KİM.9.2.8",
    zorluk: 2,
    soru: "İyonik katı (ör. NaCl) için aşağıdakilerden hangisi doğrudur?",
    aciklama: "Katı hâlde iyonlar yerlerinde titreşir, hareket edemez; bu yüzden elektriği iletmez. Sıvı hâlde veya sulu çözeltide iyonlar serbest hareket ettiği için iletkenlik sağlanır.",
    secenekler: [
      "Katı hâlde elektriği iletmezken sıvı hâlde ve sulu çözeltide iletir",
      "Hem katı hem sıvı hâlde elektriği iletir",
      "Hiçbir hâlde elektrik akımını iletmez",
      "Yalnızca gaz hâline geçince iletir",
    ],
    dogru: 0,
  },
  {
    kod: "KİM.9.2.9",
    zorluk: 2,
    soru: "Kapalı bir kaptaki sıvının buhar basıncı hangi koşulda artar?",
    aciklama: "Buhar basıncı sıvının türüne ve sıcaklığına bağlıdır. Sıcaklık artarsa buharlaşma hızlanır ve buhar basıncı artar. Sıvı miktarı veya kabın hacmi buhar basıncını değiştirmez.",
    secenekler: [
      "Sıvının sıcaklığı artırılırsa",
      "Kabın hacmi artırılırsa",
      "Sıvının miktarı artırılırsa",
      "Kap daha geniş tutulursa",
    ],
    dogru: 0,
  },
  {
    kod: "KİM.9.2.10",
    zorluk: 2,
    soru: "Bir sıvının üzerindeki dış basınç artırılırsa sıvının kaynama sıcaklığı nasıl değişir?",
    aciklama: "Kaynama, sıvının buhar basıncının dış basınca eşit olduğu sıcaklıktır. Dış basınç arttıkça kaynama için daha yüksek sıcaklık gerekir (düdüklü tencerenin çalışma ilkesi).",
    secenekler: ["Artar", "Azalır", "Değişmez", "Önce artar sonra azalır"],
    dogru: 0,
  },
  {
    kod: "KİM.9.2.11",
    zorluk: 2,
    soru: "Soğutulan balın akışkanlığının azalması (daha yavaş akması) hangi özellikle açıklanır?",
    aciklama: "Viskozite, sıvının akmaya karşı gösterdiği dirençtir. Sıcaklık düştükçe taneciklerin kinetik enerjisi azalır, moleküller arası etkileşimler daha baskın hâle gelir ve viskozite artar.",
    secenekler: [
      "Sıcaklık düştükçe viskozitenin artması",
      "Sıcaklık düştükçe yoğunluğun azalması",
      "Balın yüzey geriliminin sıfırlanması",
      "Kohezyon kuvvetinin azalması",
    ],
    dogru: 0,
  },
  {
    kod: "KİM.9.2.12",
    zorluk: 2,
    soru: "Cıvanın cam boruda dışbükey (aşağı doğru bombeli) yüzey oluşturması hangisiyle açıklanır?",
    aciklama: "Cıva tanecikleri arasındaki kohezyon kuvveti, cıva ile cam arasındaki adezyon kuvvetinden büyüktür. Bu yüzden cıva camı ıslatmaz ve dışbükey yüzey oluşturur.",
    secenekler: [
      "Cıva tanecikleri arasındaki kohezyonun, cam ile cıva arasındaki adezyondan büyük olması",
      "Adezyonun kohezyondan büyük olması",
      "Yer çekiminin etkisi",
      "Cıvanın yüksek yoğunluğu",
    ],
    dogru: 0,
  },
  {
    kod: "KİM.9.2.13",
    zorluk: 3,
    soru: "Bir iğne su yüzeyinde batmadan durabilirken aynı iğne deterjanlı suda batar. Bu gözlem hangisiyle açıklanır?",
    aciklama: "Yüzey gerilimi, sıvı yüzeyinin gerilmiş bir zar gibi davranmasıdır. Deterjan (sabun) suyun yüzey gerilimini azalttığı için iğne batar.",
    secenekler: [
      "Deterjan suyun yüzey gerilimini azaltır",
      "Deterjan suyun yüzey gerilimini artırır",
      "Deterjan kohezyon kuvvetini artırır",
      "Deterjan suyun yoğunluğunu artırır",
    ],
    dogru: 0,
  },
  // ===== U6 Kimyasal Tepkimeler (KİM.10.1.6 +1, 10.1.7 +2) =====
  {
    kod: "KİM.10.1.6",
    zorluk: 2,
    soru: "N₂ + H₂ → NH₃ tepkimesinin en küçük tam sayılarla denkleştirilmiş hâli aşağıdakilerden hangisidir?",
    aciklama: "Azot sayısını eşitlemek için NH₃'ün katsayısı 2, hidrojen sayısını eşitlemek için H₂'nin katsayısı 3 olmalıdır: N₂ + 3H₂ → 2NH₃.",
    secenekler: [
      "N₂ + 3H₂ → 2NH₃",
      "N₂ + H₂ → NH₃",
      "2N₂ + 3H₂ → 2NH₃",
      "N₂ + 2H₂ → 2NH₃",
    ],
    dogru: 0,
  },
  {
    kod: "KİM.10.1.7",
    zorluk: 2,
    soru: "2H₂ + O₂ → 2H₂O denklemine göre 4 mol H₂, yeterli O₂ ile tepkimeye girdiğinde kaç mol H₂O oluşur?",
    aciklama: "Denkleme göre H₂ ve H₂O'nun mol sayıları eşittir (2 : 2 = 1 : 1). Bu yüzden 4 mol H₂'den 4 mol H₂O oluşur.",
    secenekler: ["4", "2", "6", "8"],
    dogru: 0,
  },
  {
    kod: "KİM.10.1.7",
    zorluk: 3,
    soru: "N₂ + 3H₂ → 2NH₃ tepkimesine göre 6 mol H₂'den en fazla kaç mol NH₃ elde edilir?",
    aciklama: "Stokiyometrik oran 3 mol H₂ → 2 mol NH₃'tür. 6 mol H₂ için: 6 × (2/3) = 4 mol NH₃ oluşur.",
    secenekler: ["4", "2", "6", "3"],
    dogru: 0,
  },
  // ===== U7 Gazlar (KİM.10.1.5 +3, 10.1.8 +3, 10.1.9 +3, 10.1.11 +2) =====
  {
    kod: "KİM.10.1.5",
    zorluk: 1,
    soru: "Aynı sıcaklıkta özdeş kaplarda bulunan saf su ile saf etil alkolü hangi ölçümle kesin ayırt edebilirsin?",
    aciklama: "Yoğunluk (özkütle) saf maddeler için ayırt edici bir özelliktir; suyun ve etil alkolün yoğunlukları farklıdır. Kütle ve hacim tek başına ayırt edici değildir.",
    secenekler: [
      "Yoğunluk ölçümü",
      "Kütle ölçümü",
      "Hacim ölçümü",
      "Sıcaklık ölçümü",
    ],
    dogru: 0,
  },
  {
    kod: "KİM.10.1.5",
    zorluk: 2,
    soru: "Saf bir madde sabit basınçta erirken sıcaklığı nasıl değişir?",
    aciklama: "Saf maddeler erime süresince sıcaklığı sabit kalır (erime noktası). Karışımlarda ise erime aralığı gözlenir; bu yüzden erime noktası saflık kontrolünde kullanılır.",
    secenekler: [
      "Değişmez, sabit kalır",
      "Sürekli artar",
      "Sürekli azalır",
      "Düzensiz değişir",
    ],
    dogru: 0,
  },
  {
    kod: "KİM.10.1.5",
    zorluk: 2,
    soru: "Yoğunluğu 0,8 g/mL ölçülen bilinmeyen bir sıvı, bilinen saf maddelerin yoğunluk tablosuyla karşılaştırılıyor. Bu işlemle ilgili hangisi söylenir?",
    aciklama: "Yoğunluk ayırt edici bir özelliktir ancak farklı maddeler aynı yoğunluğa sahip olabilir. Bu yüzden ölçüm, sıvının kimliği hakkında güçlü bir tahmin sağlar ama tek başına kesin kanıt değildir.",
    secenekler: [
      "Sıvının kimliği hakkında tahmin yürütülebilir",
      "Sıvının kütlesi kesin olarak bulunmuştur",
      "Sıvının hacmi kesin olarak bulunmuştur",
      "Sıvının kesinlikle benzin olduğu kanıtlanmıştır",
    ],
    dogru: 0,
  },
  {
    kod: "KİM.10.1.8",
    zorluk: 1,
    soru: "İçi hava dolu balonun ağzı açık bırakıldığında bir süre sonra sönmesi gazların hangi özelliğiyle açıklanır?",
    aciklama: "Gaz tanecikleri sürekli hareket eder ve bulundukları kabın her yerine yayılır. Balonun ağzı açılınca hava tanecikleri dışarıya yayılır (difüzyon).",
    secenekler: [
      "Gaz taneciklerinin bulundukları kabın her yerine yayılması",
      "Gazların ağırlıksız olması",
      "Gaz taneciklerinin hareketsiz olması",
      "Gazların renkli olması",
    ],
    dogru: 0,
  },
  {
    kod: "KİM.10.1.8",
    zorluk: 1,
    soru: "Aynı sıcaklık ve basınçta 1 L helyum gazı ile 1 L oksijen gazının kütleleri farklıdır. Bu gözlemden hangi sonuca ulaşılır?",
    aciklama: "Eşit hacimdeki gazların kütleleri türüne göre farklıdır; çünkü gazların molar kütleleri farklıdır. Oksijen (32 g/mol) helyumdan (4 g/mol) ağırdır.",
    secenekler: [
      "Eşit hacimdeki gazların kütleleri türüne göre farklıdır",
      "Gazların kütlesi yoktur",
      "Bütün gazlar aynı yoğunluğa sahiptir",
      "Oksijen helyumdan hafiftir",
    ],
    dogru: 0,
  },
  {
    kod: "KİM.10.1.8",
    zorluk: 2,
    soru: "LPG tüplerinde büyük miktarda gazın küçük bir hacimde depolanabilmesi gazların hangi özelliğinden yararlanılır?",
    aciklama: "Gazlar yüksek basınçla sıkıştırılarak hacimleri büyük ölçüde küçültülebilir. Bu, gazların sıkıştırılabilir olmasının bir sonucudur.",
    secenekler: [
      "Sıkıştırılabilir olmaları",
      "Düşük yoğunlukları",
      "Renksiz olmaları",
      "Yanıcı olmaları",
    ],
    dogru: 0,
  },
  {
    kod: "KİM.10.1.9",
    zorluk: 1,
    soru: "Sabit basınçta bir gazın sıcaklığı artırılırsa hacmi nasıl değişir?",
    aciklama: "Sabit basınçta sıcaklık artarsa gaz taneciklerinin kinetik enerjisi artar ve gaz genleşir (Charles yasası). Hacim artar.",
    secenekler: ["Artar", "Azalır", "Değişmez", "Önce artar sonra azalır"],
    dogru: 0,
  },
  {
    kod: "KİM.10.1.9",
    zorluk: 1,
    soru: "Sabit hacimli kapalı bir kapta gazın sıcaklığı artırılırsa basıncı nasıl değişir?",
    aciklama: "Hacim sabitken sıcaklık artarsa tanecikler daha hızlı ve şiddetli çarpışır; kabın çeperlerine uygulanan basınç artar (Gay-Lussac yasası).",
    secenekler: ["Artar", "Azalır", "Değişmez", "Sıfır olur"],
    dogru: 0,
  },
  {
    kod: "KİM.10.1.9",
    zorluk: 2,
    soru: "Aynı sıcaklık ve basınçta eşit hacimli bütün gazlar eşit sayıda tanecik içerir. Bu ifade hangi yasadır?",
    aciklama: "Avogadro yasasına göre aynı sıcaklık ve basınçta eşit hacimli gazlar eşit sayıda tanecik (mol) içerir. Bu yasa mol-hacim ilişkisinin temelidir.",
    secenekler: [
      "Avogadro yasası",
      "Boyle yasası",
      "Charles yasası",
      "Dalton'un kısmi basınçlar yasası",
    ],
    dogru: 0,
  },
  {
    kod: "KİM.10.1.11",
    zorluk: 2,
    soru: "Odanın bir köşesinde sıkılan parfümün kokusunun bir süre sonra odanın her yerinden alınması gazların hangi olayını kanıtlar?",
    aciklama: "Parfüm molekülleri sürekli hareket ederek hava molekülleri arasında yayılır. Bu olay gazların difüzyon (yayılma) özelliğini gösterir.",
    secenekler: ["Difüzyon (yayılma)", "Sıkışma", "Yoğuşma", "Donma"],
    dogru: 0,
  },
  {
    kod: "KİM.10.1.11",
    zorluk: 2,
    soru: "Aynı sıcaklıkta hidrojen (H₂) gazının karbon dioksitten (CO₂) daha hızlı yayılmasının nedeni nedir?",
    aciklama: "Aynı sıcaklıkta gaz taneciklerinin ortalama kinetik enerjileri eşittir. Molar kütlesi küçük olan gazın (H₂) tanecik hızı büyük olduğu için daha hızlı yayılır.",
    secenekler: [
      "H₂'nin molar kütlesi daha küçüktür, tanecikleri daha hızlıdır",
      "CO₂ renkli bir gazdır",
      "H₂ yanıcı bir gazdır",
      "CO₂ havadan ağırdır",
    ],
    dogru: 0,
  },
];
