// Tamamlayıcı soru bankası (12. sınıf): her ünitede en az 15 soru hedefi için ek sorular.
// seed-questions.ts tarafından import edilir (idempotent: prompt eşleşmesiyle tekrar eklenmez).

import type { SoruKayit } from "./questions-bank-extra";

export const EK_SORULAR_DOLDUR_12: SoruKayit[] = [
  // ===== U16 İndirgenme-Yükseltgenme (KİM.12.1.1 +4, 12.1.2 +5) =====
  {
    kod: "KİM.12.1.1",
    zorluk: 2,
    soru: "2Na + Cl₂ → 2NaCl tepkimesinde sodyum (Na) için hangisi doğrudur?",
    aciklama: "Na, elektron vererek Na⁺'ya dönüşür: Na → Na⁺ + e⁻. Elektron kaybı yükseltgenmedir; Na bu tepkimede yükseltgenmiştir.",
    secenekler: [
      "Elektron vererek yükseltgenmiştir",
      "Elektron alarak indirgenmiştir",
      "Yükseltgenme basamağı değişmemiştir",
      "Elektron alışverişi yapmamıştır",
    ],
    dogru: 0,
  },
  {
    kod: "KİM.12.1.1",
    zorluk: 1,
    soru: "Aşağıdaki dönüşümlerden hangisinde yükseltgenme olayı gerçekleşmiştir?",
    aciklama: "Yükseltgenme elektron kaybıdır ve yükseltgenme basamağını artırır. Fe²⁺ → Fe³⁺ dönüşümünde demir +2'den +3'e çıkmıştır; bu bir yükseltgenmedir.",
    secenekler: ["Fe²⁺ → Fe³⁺", "Fe³⁺ → Fe²⁺", "Cl₂ → 2Cl⁻", "Cu²⁺ → Cu"],
    dogru: 0,
  },
  {
    kod: "KİM.12.1.1",
    zorluk: 3,
    soru: "H₂O₂ bileşiğinde oksijenin yükseltgenme basamağı kaçtır?",
    aciklama: "Hidrojenin yükseltgenme basamağı +1'dir; iki H için +2 olur. Bileşik nötr olduğundan iki oksijen toplam -2, her oksijen -1 yükseltgenme basamağına sahiptir.",
    secenekler: ["-1", "-2", "0", "+2"],
    dogru: 0,
  },
  {
    kod: "KİM.12.1.1",
    zorluk: 3,
    soru: "H₂O₂ → H₂O + O₂ tepkimesinde oksijenin bir kısmı indirgenirken bir kısmı yükseltgenir. Bu tür tepkimelere ne ad verilir?",
    aciklama: "Aynı elementin aynı bileşikte hem yükseltgenip hem indirgendiği tepkimelere orantısızlaşma (disproporsiyon) tepkimesi denir. Oksijen -1'den -2'ye iner ve 0'a yükselir.",
    secenekler: [
      "Orantısızlaşma (disproporsiyon) tepkimesi",
      "Nötralleşme tepkimesi",
      "Analiz tepkimesi",
      "Yer değiştirme tepkimesi",
    ],
    dogru: 0,
  },
  {
    kod: "KİM.12.1.2",
    zorluk: 2,
    soru: "Demir çivisi, mavi renkli CuSO₄ çözeltisine atıldığında çivinin yüzeyinde kırmızımsı bakır birikiyor. Bu gözlemden hangi sonuç çıkar?",
    aciklama: "Fe, Cu²⁺'yi indirgeyerek metal bakırı açığa çıkarır: Fe + Cu²⁺ → Fe²⁺ + Cu. Bir metalin başka bir metalin iyonunu indirgemesi, onun daha aktif olduğunu gösterir.",
    secenekler: [
      "Fe, Cu'dan daha aktiftir",
      "Cu, Fe'den daha aktiftir",
      "İki metal de tepkimeye girmemiştir",
      "Cu, Fe'yi çözünmüştür",
    ],
    dogru: 0,
  },
  {
    kod: "KİM.12.1.2",
    zorluk: 2,
    soru: "Çinko (Zn) gümüşten (Ag) daha aktiftir. Zn metali AgNO₃ çözeltisine atılırsa hangisi gerçekleşir?",
    aciklama: "Daha aktif metal (Zn), daha az aktif metalin (Ag) iyonunu indirger: Zn + 2Ag⁺ → Zn²⁺ + 2Ag. Zn çözünür, gümüş metali açığa çıkar.",
    secenekler: [
      "Zn çözünür, Ag metali açığa çıkar",
      "Ag çözünür, Zn metali açığa çıkar",
      "Hiçbir değişim gözlenmez",
      "Her iki metal de çözünür",
    ],
    dogru: 0,
  },
  {
    kod: "KİM.12.1.2",
    zorluk: 1,
    soru: "Metallerin aktifliği (elektron verme eğilimi) arttıkça hangisi doğrudur?",
    aciklama: "Aktiflik, elektron verme eğilimidir. Aktifliği yüksek metaller elektronlarını kolay verir, yani daha kolay yükseltgenir ve daha güçlü indirgendir.",
    secenekler: [
      "Daha kolay yükseltgenirler",
      "Daha kolay indirgenirler",
      "Daha az tepkimeye girerler",
      "Elektron alma istekleri artar",
    ],
    dogru: 0,
  },
  {
    kod: "KİM.12.1.2",
    zorluk: 2,
    soru: "Cu, Ag ve Au metallerinden hangisi en aktiftir?",
    aciklama: "Aktiflik sıralamasında Cu, Ag'den; Ag de Au'dan önce gelir. Bu üç metal arasında en aktif olanı bakırdır (Cu). Soy metaller en az aktiftir.",
    secenekler: ["Cu", "Ag", "Au", "Üçü de eşit aktiftir"],
    dogru: 0,
  },
  {
    kod: "KİM.12.1.2",
    zorluk: 3,
    soru: "Mg metali HCl ile kendiliğinden tepkimeye girip H₂ gazı açığa çıkarırken Cu metali HCl ile tepkime vermez. Bu durumdan hangi çıkarım yapılır?",
    aciklama: "Metaller, hidrojenden aktifse asitlerle tepkimeye girip H₂ açığa çıkarır. Mg hidrojenden aktiftir; Cu ise hidrojenden daha az aktif olduğu için HCl ile tepkime vermez.",
    secenekler: [
      "Mg, hidrojenden aktiftir; Cu, hidrojenden daha az aktiftir",
      "Cu, Mg'den daha aktiftir",
      "HCl yalnızca soy metallerle tepkime verir",
      "Mg zayıf bir metaldir",
    ],
    dogru: 0,
  },
  // ===== U17 Elektrokimyasal Hücreler (KİM.12.1.3 +1, 12.1.4 +1, 12.1.5 +1, 12.1.8 +1, 12.1.9 +1) =====
  {
    kod: "KİM.12.1.3",
    zorluk: 2,
    soru: "Galvanik hücrede katot elektrodunda hangi olay gerçekleşir?",
    aciklama: "Galvanik hücrede katotta indirgenme (elektron alma), anotta yükseltgenme (elektron verme) gerçekleşir. Katot pozitif (+) kutuptur.",
    secenekler: ["İndirgenme", "Yükseltgenme", "Metalin çözünmesi", "Buharlaşma"],
    dogru: 0,
  },
  {
    kod: "KİM.12.1.4",
    zorluk: 3,
    soru: "Zn²⁺/Zn için E° = -0,76 V ve Cu²⁺/Cu için E° = +0,34 V olduğuna göre Zn-Cu galvanik hücresinin standart hücre potansiyeli kaç V'tur?",
    aciklama: "Katot Cu (daha büyük E°), anot Zn'dir. E°hücre = E°katot - E°anot = +0,34 - (-0,76) = +1,10 V.",
    secenekler: ["+1,10 V", "-1,10 V", "+0,42 V", "-0,42 V"],
    dogru: 0,
  },
  {
    kod: "KİM.12.1.5",
    zorluk: 3,
    soru: "Zn | Zn²⁺ || Cu²⁺ | Cu galvanik hücresinde Cu²⁺ derişimi artırılırsa hücre potansiyeli nasıl değişir?",
    aciklama: "Hücre tepkimesi Zn + Cu²⁺ → Zn²⁺ + Cu'dur. Cu²⁺ derişimi artarsa tepkime ürünler yönünde daha kolay ilerler ve hücre potansiyeli artar (Nernst eşitliği).",
    secenekler: ["Artar", "Azalır", "Değişmez", "Sıfır olur"],
    dogru: 0,
  },
  {
    kod: "KİM.12.1.8",
    zorluk: 2,
    soru: "Nikel kaplama yapılan bir elektroliz düzeneğinde çözeltiye Ni²⁺ iyonu sağlayan ve zamanla aşınan elektrot hangisidir?",
    aciklama: "Elektrolizde anotta yükseltgenme olur: Ni → Ni²⁺ + 2e⁻. Anot zamanla aşınır, açığa çıkan Ni²⁺ iyonları katotta metalik nikel olarak birikir (kaplama).",
    secenekler: ["Anot", "Katot", "Kaplanacak cisim", "Standart hidrojen elektrodu"],
    dogru: 0,
  },
  {
    kod: "KİM.12.1.9",
    zorluk: 2,
    soru: "Toprak altındaki demir boruyu korozyondan korumak için boruya bağlanan daha aktif magnezyum çubuğunun zamanla aşınmasına ne ad verilir?",
    aciklama: "Mg, demirden daha aktiftir ve demir yerine kendisi yükseltgenir (aşınır). Böylece demir korunur; bu yönteme katodik koruma veya kurban anot yöntemi denir.",
    secenekler: [
      "Katodik koruma (kurban anot yöntemi)",
      "Pasivasyon",
      "Elektrolizle kaplama",
      "Galvanizasyon",
    ],
    dogru: 0,
  },
  // ===== U18 Organik Kimyaya Giriş (KİM.12.2.1 +3, 12.2.2 +3, 12.2.3 +3) =====
  {
    kod: "KİM.12.2.1",
    zorluk: 1,
    soru: "İki atom arasında oluşan ilk kimyasal bağ hangi türdür?",
    aciklama: "İki atom arasındaki ilk bağ her zaman sigma (σ) bağıdır. İkinci ve üçüncü bağlar pi (π) bağıdır.",
    secenekler: ["Sigma (σ) bağı", "Pi (π) bağı", "Hidrojen bağı", "Metalik bağ"],
    dogru: 0,
  },
  {
    kod: "KİM.12.2.1",
    zorluk: 2,
    soru: "Karbon atomları arasındaki üçlü bağ (C≡C) kaç sigma ve kaç pi bağı içerir?",
    aciklama: "İlk bağ sigma, sonraki bağlar pi'dir. Üçlü bağ 1 sigma + 2 pi bağından oluşur.",
    secenekler: [
      "1 sigma, 2 pi",
      "2 sigma, 1 pi",
      "3 sigma",
      "0 sigma, 3 pi",
    ],
    dogru: 0,
  },
  {
    kod: "KİM.12.2.1",
    zorluk: 2,
    soru: "Pi (π) bağı nasıl oluşur?",
    aciklama: "Pi bağı, paralel (p) orbitallerinin yan yana örtüşmesiyle oluşur. Uç uca örtüşme ise sigma bağını oluşturur.",
    secenekler: [
      "Paralel p orbitallerinin yan yana örtüşmesiyle",
      "s orbitallerinin uç uca örtüşmesiyle",
      "Çekirdeklerin birbirine yaklaşmasıyla",
      "Elektron transferiyle",
    ],
    dogru: 0,
  },
  {
    kod: "KİM.12.2.2",
    zorluk: 2,
    soru: "Eten (C₂H₄) molekülündeki karbon atomlarının hibritleşme türü nedir?",
    aciklama: "Çift bağ (C=C) yapan karbonlar sp² hibritleşmesi yapar. Eten karbonları sp² hibritlidir (üçgen düzlem, 120°).",
    secenekler: ["sp²", "sp³", "sp", "Hibritleşme yoktur"],
    dogru: 0,
  },
  {
    kod: "KİM.12.2.2",
    zorluk: 2,
    soru: "Asetilen (C₂H₂) molekülündeki karbon atomları hangi hibrit türündedir?",
    aciklama: "Üçlü bağ (C≡C) yapan karbonlar sp hibritleşmesi yapar. Asetilen karbonları sp hibritlidir (doğrusal, 180°).",
    secenekler: ["sp", "sp²", "sp³", "s"],
    dogru: 0,
  },
  {
    kod: "KİM.12.2.2",
    zorluk: 3,
    soru: "sp³ hibritleşmesi yapan karbon atomunun bağ açısı yaklaşık kaç derecedir?",
    aciklama: "sp³ hibritleşmesi dörtyüzlü (tetrahedral) geometri oluşturur ve bağ açısı yaklaşık 109,5°'dir (metan örneğinde olduğu gibi).",
    secenekler: ["109,5°", "120°", "180°", "90°"],
    dogru: 0,
  },
  {
    kod: "KİM.12.2.3",
    zorluk: 1,
    soru: "CO₂ molekülünün geometrisi aşağıdakilerden hangisidir?",
    aciklama: "CO₂'de karbon iki çift bağ yapar (O=C=O) ve bağ yapmayan elektron çifti yoktur. Molekül doğrusaldır ve bağ açısı 180°'dir.",
    secenekler: ["Doğrusal", "Kırık (açısal)", "Üçgen piramit", "Dörtyüzlü"],
    dogru: 0,
  },
  {
    kod: "KİM.12.2.3",
    zorluk: 2,
    soru: "H₂O molekülünün geometrisi aşağıdakilerden hangisidir?",
    aciklama: "Oksijenin 2 bağı ve 2 ortaklanmamış elektron çifti vardır. VSEPR'e göre H₂O kırık (açısal) geometriye sahiptir; bağ açısı yaklaşık 104,5°'dir.",
    secenekler: ["Kırık (açısal)", "Doğrusal", "Üçgen düzlem", "Kare düzlem"],
    dogru: 0,
  },
  {
    kod: "KİM.12.2.3",
    zorluk: 2,
    soru: "NH₃ molekülünün geometrisi aşağıdakilerden hangisidir?",
    aciklama: "Azotun 3 bağı ve 1 ortaklanmamış elektron çifti vardır. VSEPR'e göre NH₃ üçgen piramit geometriye sahiptir.",
    secenekler: ["Üçgen piramit", "Üçgen düzlem", "Doğrusal", "Kare düzlem"],
    dogru: 0,
  },
  // ===== U19 Organik Bileşikler (KİM.12.2.4 +1, 12.2.10 +2, 12.2.11 +2) =====
  {
    kod: "KİM.12.2.4",
    zorluk: 2,
    soru: "CH₃-CH₂-CH₃ biçimindeki propan gösterimi hangi formül türüdür?",
    aciklama: "Atomların bağlanma düzenini gösteren CH₃-CH₂-CH₃ yazımına açık (yapısal) formül denir. Kapalı formül yalnızca atom sayısını verir (C₃H₈).",
    secenekler: ["Açık formül", "Kapalı formül", "Toplam formül", "İyonik formül"],
    dogru: 0,
  },
  {
    kod: "KİM.12.2.10",
    zorluk: 2,
    soru: "CH₃OH bileşiğinin sistematik (IUPAC) adı aşağıdakilerden hangisidir?",
    aciklama: "Tek karbonlu alkollerin adı, alkan adının sonuna -ol eklenerek yazılır: metan → metanol. CH₃OH (metil alkol) IUPAC'a göre metanoldür.",
    secenekler: ["Metanol", "Metan", "Metanal", "Etanol"],
    dogru: 0,
  },
  {
    kod: "KİM.12.2.10",
    zorluk: 3,
    soru: "CH₃CH₂CH₂OH bileşiğinin sistematik adı aşağıdakilerden hangisidir?",
    aciklama: "Üç karbonlu zincir propan'dır; OH grubu zincirin uç karbonundadır (1. karbon). IUPAC adı propan-1-ol'dür.",
    secenekler: ["Propan-1-ol", "Propan-2-ol", "Propanal", "Propanoik asit"],
    dogru: 0,
  },
  {
    kod: "KİM.12.2.11",
    zorluk: 3,
    soru: "C₂H₆O kapalı formülüne sahip fonksiyonel grup izomerleri hangileridir?",
    aciklama: "C₂H₆O hem alkol hem eter olarak yazılabilir: CH₃CH₂OH (etanol) ve CH₃OCH₃ (dimetil eter). Aynı kapalı formül, farklı fonksiyonel grup → fonksiyonel grup izomerliği.",
    secenekler: [
      "Etanol ve dimetil eter",
      "Etanol ve etanal",
      "Dimetil eter ve etan",
      "Etan ve etanol",
    ],
    dogru: 0,
  },
  {
    kod: "KİM.12.2.11",
    zorluk: 2,
    soru: "Fonksiyonel grup izomerleri için aşağıdakilerden hangisi doğrudur?",
    aciklama: "Fonksiyonel grup izomerleri aynı kapalı formüle sahiptir ancak farklı fonksiyonel gruplar içerir. Örneğin C₂H₆O: etanol (-OH) ve dimetil eter (-O-).",
    secenekler: [
      "Aynı kapalı formüle sahip, farklı fonksiyonel grup içeren bileşiklerdir",
      "Aynı açık formüle sahiptirler",
      "Yalnızca alkanlarda görülür",
      "Geometri izomerlerinin diğer adıdır",
    ],
    dogru: 0,
  },
];
